# Configuration de la connexion à la base de données

In [2]:
import pandas as pd 
import cx_Oracle
import sys
import os

%pylab inline
%load_ext sql

Populating the interactive namespace from numpy and matplotlib

In [3]:
# On Linux this must be None.
# Instead, the Oracle environment must be set before Python starts.
instant_client_dir = None

if sys.platform.startswith("win"):
    instant_client_dir = r"C:\instantclient_21_3"

# On macOS (Intel x86) set the directory to your Instant Client directory
if sys.platform.startswith("darwin"):
    instant_client_dir = os.environ.get("HOME")+"/instantclient_19_8"

# This can be called at most once per process.
if instant_client_dir is not None:
    cx_Oracle.init_oracle_client(lib_dir=instant_client_dir)

utilisateur = os.environ.get("PYTHON_USER", "stag26")

connexion = os.environ.get("PYTHON_CONNECT_STRING", "51.91.76.248:15440/coursdb")

password = os.environ.get("PYTHON_PASSWORD", "Phoenix#Icar79")

print('utilisateur :',utilisateur)
print('connexion   :',connexion)
print('password    :',password)

utilisateur : stag26
connexion   : 51.91.76.248:15440/coursdb
password    : Phoenix#Icar79

# Connexion

In [4]:
connection = cx_Oracle.connect(utilisateur, password, connexion)

In [5]:
%sql oracle+cx_oracle://stag26:Phoenix#Icar79@51.91.76.248:15440/coursdb

'Connected: stag26@coursdb'

In [6]:
print(f"Version base de données : {connection.version}\n"+
      f"Utilisateur             : {connection.username}\n"+
      f"Page de code            : {connection.encoding}\n"+
      f"Chaine de connexion     : {connection.dsn}")

Version base de données : 18.0.0.0.0
Utilisateur             : stag26
Page de code            : UTF-8
Chaine de connexion     : 51.91.76.248:15440/coursdb

# Projection


>> SELECT [ ALL | DISTINCT ] <br>
>>> { [{ NOM_TABLE | ALIAS2 }.]* ,<br><br>
>>> [ [{NOM_TABLE |ALIAS2}.]COLONNE1 [AS] ALIAS1[,...]} <br><br>
>> FROM NOM_TABLE ALIAS2 <br>

In [5]:
query = """
SELECT
    *   
FROM
    categories
"""
donnees = pd.read_sql_query(query, connection)
donnees

,CODE_CATEGORIE,NOM_CATEGORIE,DESCRIPTION
0,1,Boissons,"Boissons, cafés, thés, bières"
1,2,Condiments,"Sauces, assaisonnements et épices"
2,3,Desserts,Desserts et friandises
3,4,Produits laitiers,Fromages
4,5,Pâtes et céréales,"Pains, biscuits, pâtes et céréales"
5,6,Viandes,Viandes préparées
6,7,Produits secs,"Fruits secs, raisins, autres"
7,8,Poissons et fruits de mer,"Poissons, fruits de mer, escargots"
8,9,Conserves,"Fruits, légumes en conserve et confitures"
9,10,Viande en conserve,Viande en conserve

In [10]:
%sql SELECT CODE_CLIENT, DATE_COMMANDE, NO_EMPLOYE, PORT FROM COMMANDES FETCH NEXT 5 ROWS ONLY

 * oracle+cx_oracle://stag26:***@51.91.76.248:15440/coursdb
0 rows affected.

[('CACTU', datetime.datetime(2010, 1, 21, 0, 0), 90, Decimal('96')),
 ('LONEP', datetime.datetime(2010, 1, 21, 0, 0), 79, Decimal('55.8')),
 ('EASTC', datetime.datetime(2010, 1, 21, 0, 0), 62, Decimal('64.8')),
 ('GREAL', datetime.datetime(2010, 1, 21, 0, 0), 84, Decimal('57.6')),
 ('WARTH', datetime.datetime(2010, 1, 21, 0, 0), 54, Decimal('63.9'))]

In [12]:
%sql SELECT COMMANDES.CODE_CLIENT, COMMANDES.DATE_COMMANDE, COMMANDES.NO_EMPLOYE, PORT FROM COMMANDES FETCH NEXT 5 ROWS ONLY

 * oracle+cx_oracle://stag26:***@51.91.76.248:15440/coursdb
0 rows affected.

[('CACTU', datetime.datetime(2010, 1, 21, 0, 0), 90, Decimal('96')),
 ('LONEP', datetime.datetime(2010, 1, 21, 0, 0), 79, Decimal('55.8')),
 ('EASTC', datetime.datetime(2010, 1, 21, 0, 0), 62, Decimal('64.8')),
 ('GREAL', datetime.datetime(2010, 1, 21, 0, 0), 84, Decimal('57.6')),
 ('WARTH', datetime.datetime(2010, 1, 21, 0, 0), 54, Decimal('63.9'))]

# Les constantes

In [14]:
%sql SELECT 0, -1234567890, +1234567890, -123.456, +123.456, -1E+13  FROM DUAL

 * oracle+cx_oracle://stag26:***@51.91.76.248:15440/coursdb
0 rows affected.

[(0, -1234567890, 1234567890, Decimal('-123.456'), Decimal('123.456'), -10000000000000)]

In [17]:
%sql SELECT -123, 456, +123, 456,-1E+13 FROM DUAL

 * oracle+cx_oracle://stag26:***@51.91.76.248:15440/coursdb
0 rows affected.

[(-123, 456, 123, 456, -10000000000000)]

In [18]:
%sql SELECT 'Bonjour aujourd''hui c''est le :' "Aujourd'hui", SYSDATE "Date" FROM DUAL

 * oracle+cx_oracle://stag26:***@51.91.76.248:15440/coursdb
0 rows affected.

[("Bonjour aujourd'hui c'est le :", datetime.datetime(2021, 11, 25, 12, 23, 27))]

# Opérateur de concaténation

In [19]:
%sql SELECT NO_EMPLOYE||' -- '||NOM||' -- '||PRENOM||' -- '||DATE_NAISSANCE  "Liste des employés"  FROM EMPLOYES

 * oracle+cx_oracle://stag26:***@51.91.76.248:15440/coursdb
0 rows affected.

[('70 -- Berlioz -- Jacques -- 12/10/67',),
 ('71 -- Nocella -- Guy -- 19/11/76',),
 ('72 -- Herve -- Didier -- 19/09/79',),
 ('73 -- Mangeard -- Jocelyne -- 27/12/79',),
 ('74 -- Cazade -- Anne-Claire -- 19/09/79',),
 ('75 -- Devie -- Thérèse -- 26/03/68',),
 ('76 -- Peacock -- Margaret -- 20/03/69',),
 ('77 -- Idesheim -- Annick -- 29/09/82',),
 ('78 -- Rollet -- Philippe -- 09/03/85',),
 ('79 -- Silberreiss -- Albert -- 18/08/78',),
 ('80 -- Weiss -- Sylvie -- 08/01/78',),
 ('81 -- Delorgue -- Jean -- 11/07/81',),
 ('82 -- Zonca -- Virginie -- 12/03/80',),
 ('83 -- Twardowski -- Colette -- 13/01/79',),
 ('84 -- Coutou -- Myriam -- 31/08/85',),
 ('85 -- King -- Robert -- 10/02/75',),
 ('86 -- Ragon -- André -- 21/05/89',),
 ('87 -- Dohr -- Sylvie -- 30/12/82',),
 ('88 -- Maurousset -- James -- 26/09/78',),
 ('89 -- Pouetre -- Camille-Hélène -- 16/03/87',),
 ('90 -- Montesinos -- Aline -- 31/07/72',),
 ('91 -- Aubert -- Maria -- 02/11/84',),
 ('92 -- Thomas -- Patricia -- 13/12/83',),
 ('93 -- Falatik -- Bernard -- 24/10/81',),
 ('94 -- Marielle -- Michel -- 11/12/90',),
 ('95 -- Leger -- Pierre -- 01/09/89',),
 ('96 -- Marchand -- Dominique -- 23/06/84',),
 ('97 -- Seigne -- Marie-Pierre -- 26/02/83',),
 ('98 -- Burst -- Jean-Yves -- 06/07/67',),
 ('99 -- Damas -- Lydiane -- 09/01/72',),
 ('100 -- Espeche -- Eric -- 08/02/79',),
 ('101 -- Charles -- Philippe -- 23/12/78',),
 ('102 -- Thimoleon -- Georges -- 07/09/68',),
 ('103 -- Arrambide -- Jean Pierre -- 17/02/84',),
 ('104 -- Ziliox -- Francoise -- 26/04/79',),
 ('105 -- Viry -- Yvan -- 06/08/89',),
 ('106 -- Cheutin -- Corinne -- 04/01/83',),
 ('107 -- Lombard -- Christiane -- 31/07/91',),
 ('108 -- Tourtel -- Nicole -- 20/08/69',),
 ('109 -- Lampis -- Gabrielle -- 18/07/80',),
 ('110 -- Regner -- Charles -- 04/01/79',),
 ('111 -- Teixeira -- Claudia -- 24/12/77',),
 ('1 -- Besse -- José -- 28/03/84',),
 ('2 -- Destenay -- Agnès -- 19/12/79',),
 ('3 -- Letertre -- Sylvie -- 09/01/79',),
 ('4 -- Kremser -- Arnaud -- 01/10/76',),
 ('5 -- Lamarre -- Eric -- 26/01/84',),
 ('6 -- Cleret -- Doris -- 12/07/77',),
 ('7 -- Poidatz -- Benoît -- 25/11/82',),
 ('8 -- Messelier -- Philippe -- 30/04/80',),
 ('9 -- Gardeil -- Henri -- 10/04/84',),
 ('10 -- Capharsie -- Gérard -- 05/12/74',),
 ('11 -- Belin -- Chantal -- 15/09/86',),
 ('12 -- Perny -- Sylvie -- 18/06/90',),
 ('13 -- Courty -- Jean-Louis -- 06/12/78',),
 ('14 -- Fuller -- Andrew -- 27/06/84',),
 ('15 -- Suyama -- Michael -- 30/04/78',),
 ('16 -- Malejac -- Yannick -- 17/05/66',),
 ('17 -- Blard -- Jean-Benoît -- 09/07/86',),
 ('18 -- Brasseur -- Hervé -- 29/05/80',),
 ('19 -- Pagani -- Hector -- 13/09/82',),
 ('20 -- Gerard -- Sylvie -- 29/07/82',),
 ('21 -- Poupard -- Claudette -- 16/04/67',),
 ('22 -- Piroddi -- Nathalie -- 27/06/69',),
 ('23 -- Splingart -- Lydia -- 11/09/78',),
 ('24 -- Buchanan -- Steven -- 26/11/72',),
 ('25 -- Chaussende -- Maurice -- 31/01/85',),
 ('26 -- Hanriot -- Catherine -- 19/05/69',),
 ('27 -- Maurer -- Véronique -- 19/10/65',),
 ('28 -- Davolio -- Nancy -- 26/07/77',),
 ('29 -- Frederic -- Jean Marie -- 02/10/90',),
 ('30 -- Callahan -- Laura -- 11/01/78',),
 ('31 -- Pequignot -- Guy -- 20/12/78',),
 ('32 -- Duriez -- Maurice -- 04/05/77',),
 ('33 -- Chambaud -- Axelle -- 18/11/77',),
 ('34 -- Leverling -- Janet -- 18/09/78',),
 ('35 -- Brunet -- Jean-Luc -- 02/01/83',),
 ('36 -- Cremel -- Brigitte -- 17/09/83',),
 ('37 -- Giroux -- Jean-Claude -- 28/04/79',),
 ('38 -- Perret -- Laurence -- 12/03/75',),
 ('39 -- Jenny -- Michel -- 16/06/66',),
 ('40 -- Mennetrier -- Alexandra -- 13/04/80',),
 ('41 -- Michiels -- François -- 22/06/80',),
 ('42 -- Valot -- Alain -- 05/05/89',),
 ('43 -- Steiner -- Jean -- 07/07/78',),
 ('44 -- Etienne -- Brigitte -- 26/08/78',),
 ('45 -- Gregoire -- Renée -- 25/01/82',),
 ('46 -- Guillossou -- Nadine -- 06/09/81',),
 ('47 -- Lefebvre -- Michel -- 19/02/84',),
 ('48 -- Di Clemente -- Luc -- 15/09/90',),
 ('49 -- Bettan -- Henri-Michel -- 25/05/83',),
 ('50 -- Rivat -- Jean-Louis -- 13/05/78',),
 ('51 -- Alvarez -- Marcel -- 09/07/67',),
 ('52 -- Jacquot -- Philippe -- 31/03/84',),
 ('53 -- Dodsworth -- Anne -- 30/08/77',),
 ('54 -- Petit -- Michel -- 29/12/84',),
 ('55 -- Canu -- Christian -- 21/02/79',),
 ('56 -- Bazart -- Régis -- 16/03/86',),
 ('57 -- Grangirard -- Patricia -- 04/04/77',),
 ('58 -- Barre -- Jean-Paul -- 08/09/73',),
 ('59 -- Mure -- Guy -- 17/07/90',),
 ('60 -- Jeandel -- Véronique -- 29/12/82',),
 ('61 -- Aubry -- Jean-Claude -- 10/06/84',),
 ('62 -- Kessler -- Marc -- 06/05/91',),
 ('63 -- Urbaniak -- Isabelle -- 15/07/87',),
 ('64 -- Guerdon -- Béatrice -- 28/05/71',),
 ('65 -- Griner -- Florence -- 23/09/86',),
 ('66 -- Bodard -- René -- 12/12/90',),
 ('67 -- Maillard -- Corinne -- 20/02/65',),
 ('68 -- Dupouey -- Pierre -- 13/11/85',),
 ('69 -- Clement -- Valérie -- 16/09/79',)]

In [22]:
%sql SELECT concat(concat(concat(concat(NO_EMPLOYE,' -- '),NOM),' -- '),PRENOM)  "Liste des employés"  FROM EMPLOYES

 * oracle+cx_oracle://stag26:***@51.91.76.248:15440/coursdb
0 rows affected.

[('70 -- Berlioz -- Jacques',),
 ('71 -- Nocella -- Guy',),
 ('72 -- Herve -- Didier',),
 ('73 -- Mangeard -- Jocelyne',),
 ('74 -- Cazade -- Anne-Claire',),
 ('75 -- Devie -- Thérèse',),
 ('76 -- Peacock -- Margaret',),
 ('77 -- Idesheim -- Annick',),
 ('78 -- Rollet -- Philippe',),
 ('79 -- Silberreiss -- Albert',),
 ('80 -- Weiss -- Sylvie',),
 ('81 -- Delorgue -- Jean',),
 ('82 -- Zonca -- Virginie',),
 ('83 -- Twardowski -- Colette',),
 ('84 -- Coutou -- Myriam',),
 ('85 -- King -- Robert',),
 ('86 -- Ragon -- André',),
 ('87 -- Dohr -- Sylvie',),
 ('88 -- Maurousset -- James',),
 ('89 -- Pouetre -- Camille-Hélène',),
 ('90 -- Montesinos -- Aline',),
 ('91 -- Aubert -- Maria',),
 ('92 -- Thomas -- Patricia',),
 ('93 -- Falatik -- Bernard',),
 ('94 -- Marielle -- Michel',),
 ('95 -- Leger -- Pierre',),
 ('96 -- Marchand -- Dominique',),
 ('97 -- Seigne -- Marie-Pierre',),
 ('98 -- Burst -- Jean-Yves',),
 ('99 -- Damas -- Lydiane',),
 ('100 -- Espeche -- Eric',),
 ('101 -- Charles -- Philippe',),
 ('102 -- Thimoleon -- Georges',),
 ('103 -- Arrambide -- Jean Pierre',),
 ('104 -- Ziliox -- Francoise',),
 ('105 -- Viry -- Yvan',),
 ('106 -- Cheutin -- Corinne',),
 ('107 -- Lombard -- Christiane',),
 ('108 -- Tourtel -- Nicole',),
 ('109 -- Lampis -- Gabrielle',),
 ('110 -- Regner -- Charles',),
 ('111 -- Teixeira -- Claudia',),
 ('1 -- Besse -- José',),
 ('2 -- Destenay -- Agnès',),
 ('3 -- Letertre -- Sylvie',),
 ('4 -- Kremser -- Arnaud',),
 ('5 -- Lamarre -- Eric',),
 ('6 -- Cleret -- Doris',),
 ('7 -- Poidatz -- Benoît',),
 ('8 -- Messelier -- Philippe',),
 ('9 -- Gardeil -- Henri',),
 ('10 -- Capharsie -- Gérard',),
 ('11 -- Belin -- Chantal',),
 ('12 -- Perny -- Sylvie',),
 ('13 -- Courty -- Jean-Louis',),
 ('14 -- Fuller -- Andrew',),
 ('15 -- Suyama -- Michael',),
 ('16 -- Malejac -- Yannick',),
 ('17 -- Blard -- Jean-Benoît',),
 ('18 -- Brasseur -- Hervé',),
 ('19 -- Pagani -- Hector',),
 ('20 -- Gerard -- Sylvie',),
 ('21 -- Poupard -- Claudette',),
 ('22 -- Piroddi -- Nathalie',),
 ('23 -- Splingart -- Lydia',),
 ('24 -- Buchanan -- Steven',),
 ('25 -- Chaussende -- Maurice',),
 ('26 -- Hanriot -- Catherine',),
 ('27 -- Maurer -- Véronique',),
 ('28 -- Davolio -- Nancy',),
 ('29 -- Frederic -- Jean Marie',),
 ('30 -- Callahan -- Laura',),
 ('31 -- Pequignot -- Guy',),
 ('32 -- Duriez -- Maurice',),
 ('33 -- Chambaud -- Axelle',),
 ('34 -- Leverling -- Janet',),
 ('35 -- Brunet -- Jean-Luc',),
 ('36 -- Cremel -- Brigitte',),
 ('37 -- Giroux -- Jean-Claude',),
 ('38 -- Perret -- Laurence',),
 ('39 -- Jenny -- Michel',),
 ('40 -- Mennetrier -- Alexandra',),
 ('41 -- Michiels -- François',),
 ('42 -- Valot -- Alain',),
 ('43 -- Steiner -- Jean',),
 ('44 -- Etienne -- Brigitte',),
 ('45 -- Gregoire -- Renée',),
 ('46 -- Guillossou -- Nadine',),
 ('47 -- Lefebvre -- Michel',),
 ('48 -- Di Clemente -- Luc',),
 ('49 -- Bettan -- Henri-Michel',),
 ('50 -- Rivat -- Jean-Louis',),
 ('51 -- Alvarez -- Marcel',),
 ('52 -- Jacquot -- Philippe',),
 ('53 -- Dodsworth -- Anne',),
 ('54 -- Petit -- Michel',),
 ('55 -- Canu -- Christian',),
 ('56 -- Bazart -- Régis',),
 ('57 -- Grangirard -- Patricia',),
 ('58 -- Barre -- Jean-Paul',),
 ('59 -- Mure -- Guy',),
 ('60 -- Jeandel -- Véronique',),
 ('61 -- Aubry -- Jean-Claude',),
 ('62 -- Kessler -- Marc',),
 ('63 -- Urbaniak -- Isabelle',),
 ('64 -- Guerdon -- Béatrice',),
 ('65 -- Griner -- Florence',),
 ('66 -- Bodard -- René',),
 ('67 -- Maillard -- Corinne',),
 ('68 -- Dupouey -- Pierre',),
 ('69 -- Clement -- Valérie',)]

# Opérateurs arithmétiques

Une expression arithmétique est une combinaison de noms de colonnes, de constantes et de fonctions arithmétiques (les fonctions arithmétiques sont traitées plus loin) combinées au moyen des opérateurs arithmétiques addition « + », soustraction « - », multiplication « * » ou division « / ».

In [26]:
%sql \
SELECT NOM_PRODUIT "Produit", PRIX_UNITAIRE*UNITES_STOCK "Stock",\
       UNITES_COMMANDEES*12 "Commandes" \
FROM PRODUITS

 * oracle+cx_oracle://stag26:***@51.91.76.248:15440/coursdb
0 rows affected.

[('Chai', 3510, None),
 ('Chang', 1615, 480),
 ('Aniseed Syrup', 650, 840),
 ("Chef Anton's Cajun Seasoning", 5830, None),
 ("Grandma's Boysenberry Spread", 15000, None),
 ("Uncle Bob's Organic Dried Pears", 2250, None),
 ('Northwoods Cranberry Sauce', 1200, None),
 ('Mishi Kobe Niku', None, None),
 ('Ikura', 4805, None),
 ('Queso Cabrales', 2310, 360),
 ('Queso Manchego La Pastora', 16340, None),
 ('Konbu', 720, None),
 ('Alice Mutton', None, None),
 ('Teatime Chocolate Biscuits', 1150, None),
 ("Sir Rodney's Marmalade", 16200, None),
 ("Sir Rodney's Scones", 150, 480),
 ("Gustaf's Knäckebröd", 10920, None),
 ('Tunnbröd', 2745, None),
 ('NuNuCa Nuß-Nougat-Creme', 5320, None),
 ('Rössle Sauerkraut', None, None),
 ('Mascarpone Fabioli', 1440, 480),
 ('Sasquatch Ale', 7770, None),
 ('Steeleye Stout', 1800, None),
 ('Inlagd Sill', 10640, None),
 ('Gravad lax', 1430, 600),
 ('Chartreuse verte', 6210, None),
 ('Boston Crab Meat', 11316, None),
 ('Singaporean Hokkien Fried Mee', None, None),
 ('Ipoh Coffee', 3910, 120),
 ('Spegesild', 5700, None),
 ('Maxilaku', 1000, 720),
 ('Manjimup Dried Apples', 5300, None),
 ('Filo Mix', 1330, None),
 ('Perth Pasties', None, None),
 ('Pâté chinois', 13800, None),
 ('Gnocchi di nonna Alice', 3990, 120),
 ('Raclette Courdavault', 21725, None),
 ('Camembert Pierrot', 3230, None),
 ('Louisiana Hot Spiced Okra', 340, 1200),
 ('Laughing Lumberjack Lager', 3640, None),
 ('Gudbrandsdalsost', 4680, None),
 ('Outback Lager', 1125, 120),
 ('Mozzarella di Giovanni', 2436, None),
 ('Röd Kaviar', 7575, None),
 ('Longlife Tofu', 200, 240),
 ('Lakkalikööri', 5130, None),
 ('Original Frankfurter grüne Soße', 2080, None),
 ("Chef Anton's Gumbo Mix", 0, None),
 ('Tofu', 4060, None),
 ('Genen Shouyu', 3042, None),
 ('Pavlova', 2523, None),
 ('Carnarvon Tigers', 13146, None),
 ('Guaraná Fantástica', None, None),
 ('Gumbär Gummibärchen', 2340, None),
 ('Schoggi Schokolade', 10780, None),
 ('Thüringer Rostbratwurst', None, None),
 ('Nord-Ost Matjeshering', 1290, None),
 ('Gorgonzola Telino', 0, 840),
 ('Geitost', 1456, None),
 ('Côte de Blaye', 22406, None),
 ("Jack's New England Clam Chowder", 4080, None),
 ('Gula Malacca', 2619, None),
 ('Røgede sild', 240, 840),
 ('Zaanse koeken', 1728, None),
 ('Chocolade', 960, 840),
 ('Valkoinen suklaa', 5265, None),
 ('Tourtière', 777, None),
 ('Ravioli Angelo', 3528, None),
 ('Escargots de Bourgogne', 4092, None),
 ("Sirop d'érable", 16159, None),
 ('Tarte au sucre', 4199, None),
 ('Vegie-spread', 5280, None),
 ('Wimmers gute Semmelknödel', 3652, 960),
 ('Louisiana Fiery Hot Pepper Sauce', 7980, None),
 ('Scottish Longbreads', 378, 120),
 ('Fløtemysost', 2808, None),
 ('Rhönbräu Klosterbier', 4875, None),
 ('Syrup', 750, 300),
 ('Cajun Seasoning', 660, 120),
 ('Les Comptoirs  - Olive Oil', Decimal('640.4'), 120),
 ('Boysenberry Spread', 1875, 300),
 ('Dried Pears', 900, 120),
 ('Curry Sauce', 1200, 120),
 ('Walnuts', Decimal('697.6'), 120),
 ('Fruit Cocktail', 1170, 120),
 ('Chocolate Biscuits Mix', 138, 60),
 ('Marmalade', 2430, 120),
 ('Scones', 150, 60),
 ('Beer', 630, 180),
 ('Crab Meat', 1656, 360),
 ('Clam Chowder', Decimal('289.6'), 120),
 ('Coffee', 3450, 300),
 ('Dried Apples', 1590, 120),
 ('Long Grain Rice', 525, 300),
 ('Long Grain Rice - Gnocchi', 3420, 360),
 ('Ravioli', Decimal('1170.4'), 240),
 ('Hot Pepper Sauce', Decimal('631.6'), 120),
 ('Tomato Sauce', 1020, 240),
 ('Mozzarella', 1044, 120),
 ('Amandes', 150, 60),
 ('Mustard', 585, 180),
 ('Dried Plums', 225, 600),
 ('Green Tea', 250, 1200),
 ('Granola', 200, 240),
 ('Potato Chips', 98, 360),
 ('Brownie Mix', 180, 120),
 ('Cake Mix', 210, 120),
 ('Tea', 100, 240),
 ('Pears', 40, 120),
 ('Peaches', 40, 120),
 ('Pineapple', 40, 120),
 ('Cherry Pie Filling', 40, 120),
 ('Green Beans', 40, 120),
 ('Corn', 40, 120),
 ('Peas', 40, 120),
 ('Tuna Fish', Decimal('24.5'), 360),
 ('Smoked Salmon', 100, 360),
 ('Hot Cereal', 180, 600),
 ('Vegetable Soup', 25, 1200),
 ('Chicken Soup', 60, 1080)]

In [25]:
%sql \
SELECT NOM||' '||PRENOM "Employé", SALAIRE * 1.1 "Nouveau Salaire"\
FROM EMPLOYES

 * oracle+cx_oracle://stag26:***@51.91.76.248:15440/coursdb
0 rows affected.

[('Berlioz Jacques', 10340),
 ('Nocella Guy', 8360),
 ('Herve Didier', 7370),
 ('Mangeard Jocelyne', 9020),
 ('Cazade Anne-Claire', 7920),
 ('Devie Thérèse', 1694),
 ('Peacock Margaret', 6710),
 ('Idesheim Annick', 8030),
 ('Rollet Philippe', 5500),
 ('Silberreiss Albert', 10120),
 ('Weiss Sylvie', 7260),
 ('Delorgue Jean', 6490),
 ('Zonca Virginie', 7370),
 ('Twardowski Colette', 10340),
 ('Coutou Myriam', 7590),
 ('King Robert', 7920),
 ('Ragon André', 14300),
 ('Dohr Sylvie', 9020),
 ('Maurousset James', 8910),
 ('Pouetre Camille-Hélène', 2200),
 ('Montesinos Aline', 9570),
 ('Aubert Maria', 5610),
 ('Thomas Patricia', 7810),
 ('Falatik Bernard', 8360),
 ('Marielle Michel', 7810),
 ('Leger Pierre', 20900),
 ('Marchand Dominique', 7590),
 ('Seigne Marie-Pierre', 10560),
 ('Burst Jean-Yves', 8470),
 ('Damas Lydiane', 8470),
 ('Espeche Eric', 7150),
 ('Charles Philippe', 6600),
 ('Thimoleon Georges', 8800),
 ('Arrambide Jean Pierre', 5940),
 ('Ziliox Francoise', 2090),
 ('Viry Yvan', 7370),
 ('Cheutin Corinne', 11000),
 ('Lombard Christiane', 7040),
 ('Tourtel Nicole', 8910),
 ('Lampis Gabrielle', 1430),
 ('Regner Charles', 10230),
 ('Teixeira Claudia', 7480),
 ('Besse José', 10890),
 ('Destenay Agnès', 10890),
 ('Letertre Sylvie', 6160),
 ('Kremser Arnaud', 6600),
 ('Lamarre Eric', 8580),
 ('Cleret Doris', 8690),
 ('Poidatz Benoît', 7260),
 ('Messelier Philippe', 10450),
 ('Gardeil Henri', 8580),
 ('Capharsie Gérard', 10340),
 ('Belin Chantal', 11000),
 ('Perny Sylvie', 7150),
 ('Courty Jean-Louis', 10890),
 ('Fuller Andrew', 105600),
 ('Suyama Michael', 9240),
 ('Malejac Yannick', 9570),
 ('Blard Jean-Benoît', 6490),
 ('Brasseur Hervé', 161700),
 ('Pagani Hector', 7150),
 ('Gerard Sylvie', 9020),
 ('Poupard Claudette', 1980),
 ('Piroddi Nathalie', 7370),
 ('Splingart Lydia', 17600),
 ('Buchanan Steven', 14300),
 ('Chaussende Maurice', 7260),
 ('Hanriot Catherine', 9130),
 ('Maurer Véronique', 1540),
 ('Davolio Nancy', 9020),
 ('Frederic Jean Marie', 8910),
 ('Callahan Laura', 1320),
 ('Pequignot Guy', 6820),
 ('Duriez Maurice', 10010),
 ('Chambaud Axelle', 13200),
 ('Leverling Janet', 8140),
 ('Brunet Jean-Luc', 7260),
 ('Cremel Brigitte', 7590),
 ('Giroux Jean-Claude', 165000),
 ('Perret Laurence', 10450),
 ('Jenny Michel', 10780),
 ('Mennetrier Alexandra', 9570),
 ('Michiels François', 6050),
 ('Valot Alain', 10120),
 ('Steiner Jean', 5940),
 ('Etienne Brigitte', 2200),
 ('Gregoire Renée', 8800),
 ('Guillossou Nadine', 5720),
 ('Lefebvre Michel', 10120),
 ('Di Clemente Luc', 9240),
 ('Bettan Henri-Michel', 6050),
 ('Rivat Jean-Louis', 5720),
 ('Alvarez Marcel', 7920),
 ('Jacquot Philippe', 9790),
 ('Dodsworth Anne', 9680),
 ('Petit Michel', 6930),
 ('Canu Christian', 6380),
 ('Bazart Régis', 9790),
 ('Grangirard Patricia', 1870),
 ('Barre Jean-Paul', 9680),
 ('Mure Guy', 9020),
 ('Jeandel Véronique', 10120),
 ('Aubry Jean-Claude', 10450),
 ('Kessler Marc', 7480),
 ('Urbaniak Isabelle', 7700),
 ('Guerdon Béatrice', 1870),
 ('Griner Florence', 8910),
 ('Bodard René', 6050),
 ('Maillard Corinne', 7260),
 ('Dupouey Pierre', 6050),
 ('Clement Valérie', 7920)]

In [28]:
%sql \
SELECT NOM,DATE_NAISSANCE,DATE_NAISSANCE+1,\
      (SYSDATE-DATE_NAISSANCE)/365 "jours" FROM EMPLOYES

 * oracle+cx_oracle://stag26:***@51.91.76.248:15440/coursdb
0 rows affected.

[('Berlioz', datetime.datetime(1967, 10, 12, 0, 0), datetime.datetime(1967, 10, 13, 0, 0), Decimal('54.16033089167935058346017250126839167945')),
 ('Nocella', datetime.datetime(1976, 11, 19, 0, 0), datetime.datetime(1976, 11, 20, 0, 0), Decimal('45.04800212455606291222729578893962455616')),
 ('Herve', datetime.datetime(1979, 9, 19, 0, 0), datetime.datetime(1979, 9, 20, 0, 0), Decimal('42.2151254122272957889396245560629122274')),
 ('Mangeard', datetime.datetime(1979, 12, 27, 0, 0), datetime.datetime(1979, 12, 28, 0, 0), Decimal('41.94389253551496702181633688483003551507')),
 ('Cazade', datetime.datetime(1979, 9, 19, 0, 0), datetime.datetime(1979, 9, 20, 0, 0), Decimal('42.2151254122272957889396245560629122274')),
 ('Devie', datetime.datetime(1968, 3, 26, 0, 0), datetime.datetime(1968, 3, 27, 0, 0), Decimal('53.70553637113140537798072044647387113151')),
 ('Peacock', datetime.datetime(1969, 3, 20, 0, 0), datetime.datetime(1969, 3, 21, 0, 0), Decimal('52.72197472729578893962455606291222729589')),
 ('Idesheim', datetime.datetime(1982, 9, 29, 0, 0), datetime.datetime(1982, 9, 30, 0, 0), Decimal('39.18498842592592592592592592592592592603')),
 ('Rollet', datetime.datetime(1985, 3, 9, 0, 0), datetime.datetime(1985, 3, 10, 0, 0), Decimal('36.74115280948756976154236428209030948767')),
 ('Silberreiss', datetime.datetime(1978, 8, 18, 0, 0), datetime.datetime(1978, 8, 19, 0, 0), Decimal('43.30279664510400811770674784373414510411')),
 ('Weiss', datetime.datetime(1978, 1, 8, 0, 0), datetime.datetime(1978, 1, 9, 0, 0), Decimal('43.9110158231861998985286656519533231863')),
 ('Delorgue', datetime.datetime(1981, 7, 11, 0, 0), datetime.datetime(1981, 7, 12, 0, 0), Decimal('40.40416650811770674784373414510400811781')),
 ('Zonca', datetime.datetime(1980, 3, 12, 0, 0), datetime.datetime(1980, 3, 13, 0, 0), Decimal('41.73567335743277524099441907661085743288')),
 ('Twardowski', datetime.datetime(1979, 1, 13, 0, 0), datetime.datetime(1979, 1, 14, 0, 0), Decimal('42.89731719304921359715880263825469304932')),
 ('Coutou', datetime.datetime(1985, 8, 31, 0, 0), datetime.datetime(1985, 9, 1, 0, 0), Decimal('36.26170075469304921359715880263825469315')),
 ('King', datetime.datetime(1975, 2, 10, 0, 0), datetime.datetime(1975, 2, 11, 0, 0), Decimal('46.82334459030948756976154236428209030959')),
 ('Ragon', datetime.datetime(1989, 5, 21, 0, 0), datetime.datetime(1989, 5, 22, 0, 0), Decimal('32.53841308346017250126839167935058346027')),
 ('Dohr', datetime.datetime(1982, 12, 30, 0, 0), datetime.datetime(1982, 12, 31, 0, 0), Decimal('38.93293363140537798072044647387113140548')),
 ('Maurousset', datetime.datetime(1978, 9, 26, 0, 0), datetime.datetime(1978, 9, 27, 0, 0), Decimal('43.19594733003551496702181633688483003562')),
 ('Pouetre', datetime.datetime(1987, 3, 16, 0, 0), datetime.datetime(1987, 3, 17, 0, 0), Decimal('34.72197472729578893962455606291222729589')),
 ('Montesinos', datetime.datetime(1972, 7, 31, 0, 0), datetime.datetime(1972, 8, 1, 0, 0), Decimal('49.35485143962455606291222729578893962466')),
 ('Aubert', datetime.datetime(1984, 11, 2, 0, 0), datetime.datetime(1984, 11, 3, 0, 0), Decimal('37.08909801496702181633688483003551496712')),
 ('Thomas', datetime.datetime(1983, 12, 13, 0, 0), datetime.datetime(1983, 12, 14, 0, 0), Decimal('37.97950897387113140537798072044647387123')),
 ('Falatik', datetime.datetime(1981, 10, 24, 0, 0), datetime.datetime(1981, 10, 25, 0, 0), Decimal('40.1164952752409944190766108574327752411')),
 ('Marielle', datetime.datetime(1990, 12, 11, 0, 0), datetime.datetime(1990, 12, 12, 0, 0), Decimal('30.97950897387113140537798072044647387123')),
 ('Leger', datetime.datetime(1989, 9, 1, 0, 0), datetime.datetime(1989, 9, 2, 0, 0), Decimal('32.25622130263825469304921359715880263836')),
 ('Marchand', datetime.datetime(1984, 6, 23, 0, 0), datetime.datetime(1984, 6, 24, 0, 0), Decimal('37.45074185058346017250126839167935058356')),
 ('Seigne', datetime.datetime(1983, 2, 26, 0, 0), datetime.datetime(1983, 2, 27, 0, 0), Decimal('38.77402952181633688483003551496702181644')),
 ('Burst', datetime.datetime(1967, 7, 6, 0, 0), datetime.datetime(1967, 7, 7, 0, 0), Decimal('54.42882404236428209030948756976154236438')),
 ('Damas', datetime.datetime(1972, 1, 9, 0, 0), datetime.datetime(1972, 1, 10, 0, 0), Decimal('49.9137555492135971588026382546930492137')),
 ('Espeche', datetime.datetime(1979, 2, 8, 0, 0), datetime.datetime(1979, 2, 9, 0, 0), Decimal('42.82608431633688483003551496702181633699')),
 ('Charles', datetime.datetime(1978, 12, 23, 0, 0), datetime.datetime(1978, 12, 24, 0, 0), Decimal('42.95485143962455606291222729578893962466')),
 ('Thimoleon', datetime.datetime(1968, 9, 7, 0, 0), datetime.datetime(1968, 9, 8, 0, 0), Decimal('53.25348157661085743277524099441907661096')),
 ('Arrambide', datetime.datetime(1984, 2, 17, 0, 0), datetime.datetime(1984, 2, 18, 0, 0), Decimal('37.79868705606291222729578893962455606301')),
 ('Ziliox', datetime.datetime(1979, 4, 26, 0, 0), datetime.datetime(1979, 4, 27, 0, 0), Decimal('42.6151254122272957889396245560629122274')),
 ('Viry', datetime.datetime(1989, 8, 6, 0, 0), datetime.datetime(1989, 8, 7, 0, 0), Decimal('32.32745417935058346017250126839167935068')),
 ('Cheutin', datetime.datetime(1983, 1, 4, 0, 0), datetime.datetime(1983, 1, 5, 0, 0), Decimal('38.91923500126839167935058346017250126849')),
 ('Lombard', datetime.datetime(1991, 7, 31, 0, 0), datetime.datetime(1991, 8, 1, 0, 0), Decimal('30.34389253551496702181633688483003551507')),
 ('Tourtel', datetime.datetime(1969, 8, 20, 0, 0), datetime.datetime(1969, 8, 21, 0, 0), Decimal('52.30279664510400811770674784373414510411')),
 ('Lampis', datetime.datetime(1980, 7, 18, 0, 0), datetime.datetime(1980, 7, 19, 0, 0), Decimal('41.38498842592592592592592592592592592603')),
 ('Regner', datetime.datetime(1979, 1, 4, 0, 0), datetime.datetime(1979, 1, 5, 0, 0), Decimal('42.92197472729578893962455606291222729589')),
 ('Teixeira', datetime.datetime(1977, 12, 24, 0, 0), datetime.datetime(1977, 12, 25, 0, 0), Decimal('43.95211171359715880263825469304921359726')),
 ('Besse', datetime.datetime(1984, 3, 28, 0, 0), datetime.datetime(1984, 3, 29, 0, 0), Decimal('37.68909801496702181633688483003551496712')),
 ('Destenay', datetime.datetime(1979, 12, 19, 0, 0), datetime.datetime(1979, 12, 20, 0, 0), Decimal('41.96581034373414510400811770674784373425')),
 ('Letertre', datetime.datetime(1979, 1, 9, 0, 0), datetime.datetime(1979, 1, 10, 0, 0), Decimal('42.9082760971588026382546930492135971589')),
 ('Kremser', datetime.datetime(1976, 10, 1, 0, 0), datetime.datetime(1976, 10, 2, 0, 0), Decimal('45.18224869989852866565195332318619989863')),
 ('Lamarre', datetime.datetime(1984, 1, 26, 0, 0), datetime.datetime(1984, 1, 27, 0, 0), Decimal('37.85896102866565195332318619989852866575')),
 ('Cleret', datetime.datetime(1977, 7, 12, 0, 0), datetime.datetime(1977, 7, 13, 0, 0), Decimal('44.40416650811770674784373414510400811781')),
 ('Poidatz', datetime.datetime(1982, 11, 25, 0, 0), datetime.datetime(1982, 11, 26, 0, 0), Decimal('39.02882404236428209030948756976154236438')),
 ('Messelier', datetime.datetime(1980, 4, 30, 0, 0), datetime.datetime(1980, 5, 1, 0, 0), Decimal('41.60142678209030948756976154236428209041')),
 ('Gardeil', datetime.datetime(1984, 4, 10, 0, 0), datetime.datetime(1984, 4, 11, 0, 0), Decimal('37.65348157661085743277524099441907661096')),
 ('Capharsie', datetime.datetime(1974, 12, 5, 0, 0), datetime.datetime(1974, 12, 6, 0, 0), Decimal('47.00690623414510400811770674784373414521')),
 ('Belin', datetime.datetime(1986, 9, 15, 0, 0), datetime.datetime(1986, 9, 16, 0, 0), Decimal('35.22060486428209030948756976154236428219')),
 ('Perny', datetime.datetime(1990, 6, 18, 0, 0), datetime.datetime(1990, 6, 19, 0, 0), Decimal('31.46170075469304921359715880263825469315')),
 ('Courty', datetime.datetime(1978, 12, 6, 0, 0), datetime.datetime(1978, 12, 7, 0, 0), Decimal('43.00142678209030948756976154236428209041')),
 ('Fuller', datetime.datetime(1984, 6, 27, 0, 0), datetime.datetime(1984, 6, 28, 0, 0), Decimal('37.43978294647387113140537798072044647397')),
 ('Suyama', datetime.datetime(1978, 4, 30, 0, 0), datetime.datetime(1978, 5, 1, 0, 0), Decimal('43.60416650811770674784373414510400811781')),
 ('Malejac', datetime.datetime(1966, 5, 17, 0, 0), datetime.datetime(1966, 5, 18, 0, 0), Decimal('55.56581034373414510400811770674784373425')),
 ('Blard', datetime.datetime(1986, 7, 9, 0, 0), datetime.datetime(1986, 7, 10, 0, 0), Decimal('35.40690623414510400811770674784373414521')),
 ('Brasseur', datetime.datetime(1980, 5, 29, 0, 0), datetime.datetime(1980, 5, 30, 0, 0), Decimal('41.52197472729578893962455606291222729589')),
 ('Pagani', datetime.datetime(1982, 9, 13, 0, 0), datetime.datetime(1982, 9, 14, 0, 0), Decimal('39.22882404236428209030948756976154236438')),
 ('Gerard', datetime.datetime(1982, 7, 29, 0, 0), datetime.datetime(1982, 7, 30, 0, 0), Decimal('39.35485143962455606291222729578893962466')),
 ('Poupard', datetime.datetime(1967, 4, 16, 0, 0), datetime.datetime(1967, 4, 17, 0, 0), Decimal('54.65074185058346017250126839167935058356')),
 ('Piroddi', datetime.datetime(1969, 6, 27, 0, 0), datetime.datetime(1969, 6, 28, 0, 0), Decimal('52.45074185058346017250126839167935058356')),
 ('Splingart', datetime.datetime(1978, 9, 11, 0, 0), datetime.datetime(1978, 9, 12, 0, 0), Decimal('43.23704322044647387113140537798072044658')),
 ('Buchanan', datetime.datetime(1972, 11, 26, 0, 0), datetime.datetime(1972, 11, 27, 0, 0), Decimal('49.03156376839167935058346017250126839178')),
 ('Chaussende', datetime.datetime(1985, 1, 31, 0, 0), datetime.datetime(1985, 2, 1, 0, 0), Decimal('36.84252267250126839167935058346017250137')),
 ('Hanriot', datetime.datetime(1969, 5, 19, 0, 0), datetime.datetime(1969, 5, 20, 0, 0), Decimal('52.55759116565195332318619989852866565205')),
 ('Maurer', datetime.datetime(1965, 10, 19, 0, 0), datetime.datetime(1965, 10, 20, 0, 0), Decimal('56.14115280948756976154236428209030948767')),
 ('Davolio', datetime.datetime(1977, 7, 26, 0, 0), datetime.datetime(1977, 7, 27, 0, 0), Decimal('44.36581034373414510400811770674784373425')),
 ('Frederic', datetime.datetime(1990, 10, 2, 0, 0), datetime.datetime(1990, 10, 3, 0, 0), Decimal('31.17128979578893962455606291222729578904')),
 ('Callahan', datetime.datetime(1978, 1, 11, 0, 0), datetime.datetime(1978, 1, 12, 0, 0), Decimal('43.90279664510400811770674784373414510411')),
 ('Pequignot', datetime.datetime(1978, 12, 20, 0, 0), datetime.datetime(1978, 12, 21, 0, 0), Decimal('42.96307061770674784373414510400811770685')),
 ('Duriez', datetime.datetime(1977, 5, 4, 0, 0), datetime.datetime(1977, 5, 5, 0, 0), Decimal('44.59320760400811770674784373414510400822')),
 ('Chambaud', datetime.datetime(1977, 11, 18, 0, 0), datetime.datetime(1977, 11, 19, 0, 0), Decimal('44.05074185058346017250126839167935058356')),
 ('Leverling', datetime.datetime(1978, 9, 18, 0, 0), datetime.datetime(1978, 9, 19, 0, 0), Decimal('43.21786513825469304921359715880263825479')),
 ('Brunet', datetime.datetime(1983, 1, 2, 0, 0), datetime.datetime(1983, 1, 3, 0, 0), Decimal('38.92471445332318619989852866565195332329')),
 ('Cremel', datetime.datetime(1983, 9, 17, 0, 0), datetime.datetime(1983, 9, 18, 0, 0), Decimal('38.21786513825469304921359715880263825479')),
 ('Giroux', datetime.datetime(1979, 4, 28, 0, 0), datetime.datetime(1979, 4, 29, 0, 0), Decimal('42.6096459601725012683916793505834601726')),
 ('Perret', datetime.datetime(1975, 3, 12, 0, 0), datetime.datetime(1975, 3, 13, 0, 0), Decimal('46.74115280948756976154236428209030948767')),
 ('Jenny', datetime.datetime(1966, 6, 16, 0, 0), datetime.datetime(1966, 6, 17, 0, 0), Decimal('55.48361856291222729578893962455606291233')),
 ('Mennetrier', datetime.datetime(1980, 4, 13, 0, 0), datetime.datetime(1980, 4, 14, 0, 0), Decimal('41.64800212455606291222729578893962455616')),
 ('Michiels', datetime.datetime(1980, 6, 22, 0, 0), datetime.datetime(1980, 6, 23, 0, 0), Decimal('41.45622130263825469304921359715880263836')),
 ('Valot', datetime.datetime(1989, 5, 5, 0, 0), datetime.datetime(1989, 5, 6, 0, 0), Decimal('32.58224869989852866565195332318619989863')),
 ('Steiner', datetime.datetime(1978, 7, 7, 0, 0), datetime.datetime(1978, 7, 8, 0, 0), Decimal('43.41786513825469304921359715880263825479')),
 ('Etienne', datetime.datetime(1978, 8, 26, 0, 0), datetime.datetime(1978, 8, 27, 0, 0), Decimal('43.28087883688483003551496702181633688493')),
 ('Gregoire', datetime.datetime(1982, 1, 25, 0, 0), datetime.datetime(1982, 1, 26, 0, 0), Decimal('39.86170075469304921359715880263825469315')),
 ('Guillossou', datetime.datetime(1981, 9, 6, 0, 0), datetime.datetime(1981, 9, 7, 0, 0), Decimal('40.24800212455606291222729578893962455616')),
 ('Lefebvre', datetime.datetime(1984, 2, 19, 0, 0), datetime.datetime(1984, 2, 20, 0, 0), Decimal('37.79320760400811770674784373414510400822')),
 ('Di Clemente', datetime.datetime(1990, 9, 15, 0, 0), datetime.datetime(1990, 9, 16, 0, 0), Decimal('31.21786513825469304921359715880263825479')),
 ('Bettan', datetime.datetime(1983, 5, 25, 0, 0), datetime.datetime(1983, 5, 26, 0, 0), Decimal('38.53293363140537798072044647387113140548')),
 ('Rivat', datetime.datetime(1978, 5, 13, 0, 0), datetime.datetime(1978, 5, 14, 0, 0), Decimal('43.56855006976154236428209030948756976164')),
 ('Alvarez', datetime.datetime(1967, 7, 9, 0, 0), datetime.datetime(1967, 7, 10, 0, 0), Decimal('54.42060486428209030948756976154236428219')),
 ('Jacquot', datetime.datetime(1984, 3, 31, 0, 0), datetime.datetime(1984, 4, 1, 0, 0), Decimal('37.68087883688483003551496702181633688493')),
 ('Dodsworth', datetime.datetime(1977, 8, 30, 0, 0), datetime.datetime(1977, 8, 31, 0, 0), Decimal('44.26991993277524099441907661085743277534')),
 ('Petit', datetime.datetime(1984, 12, 29, 0, 0), datetime.datetime(1984, 12, 30, 0, 0), Decimal('36.93293363140537798072044647387113140548')),
 ('Canu', datetime.datetime(1979, 2, 21, 0, 0), datetime.datetime(1979, 2, 22, 0, 0), Decimal('42.79046787798072044647387113140537798082')),
 ('Bazart', datetime.datetime(1986, 3, 16, 0, 0), datetime.datetime(1986, 3, 17, 0, 0), Decimal('35.72197472729578893962455606291222729589')),
 ('Grangirard', datetime.datetime(1977, 4, 4, 0, 0), datetime.datetime(1977, 4, 5, 0, 0), Decimal('44.67539938483003551496702181633688483014')),
 ('Barre', datetime.datetime(1973, 9, 8, 0, 0), datetime.datetime(1973, 9, 9, 0, 0), Decimal('48.24800212455606291222729578893962455616')),
 ('Mure', datetime.datetime(1990, 7, 17, 0, 0), datetime.datetime(1990, 7, 18, 0, 0), Decimal('31.38224869989852866565195332318619989863')),
 ('Jeandel', datetime.datetime(1982, 12, 29, 0, 0), datetime.datetime(1982, 12, 30, 0, 0), Decimal('38.93567335743277524099441907661085743288')),
 ('Aubry', datetime.datetime(1984, 6, 10, 0, 0), datetime.datetime(1984, 6, 11, 0, 0), Decimal('37.48635828893962455606291222729578893973')),
 ('Kessler', datetime.datetime(1991, 5, 6, 0, 0), datetime.datetime(1991, 5, 7, 0, 0), Decimal('30.57950897387113140537798072044647387123')),
 ('Urbaniak', datetime.datetime(1987, 7, 15, 0, 0), datetime.datetime(1987, 7, 16, 0, 0), Decimal('34.39046787798072044647387113140537798082')),
 ('Guerdon', datetime.datetime(1971, 5, 28, 0, 0), datetime.datetime(1971, 5, 29, 0, 0), Decimal('50.53293363140537798072044647387113140548')),
 ('Griner', datetime.datetime(1986, 9, 23, 0, 0), datetime.datetime(1986, 9, 24, 0, 0), Decimal('35.19868705606291222729578893962455606301')),
 ('Bodard', datetime.datetime(1990, 12, 12, 0, 0), datetime.datetime(1990, 12, 13, 0, 0), Decimal('30.97676924784373414510400811770674784384')),
 ('Maillard', datetime.datetime(1965, 2, 20, 0, 0), datetime.datetime(1965, 2, 21, 0, 0), Decimal('56.80142678209030948756976154236428209041')),
 ('Dupouey', datetime.datetime(1985, 11, 13, 0, 0), datetime.datetime(1985, 11, 14, 0, 0), Decimal('36.05896102866565195332318619989852866575')),
 ('Clement', datetime.datetime(1979, 9, 16, 0, 0), datetime.datetime(1979, 9, 17, 0, 0), Decimal('42.22334459030948756976154236428209030959'))]

# La valeur NULL

In [29]:
%sql \
SELECT NOM, SALAIRE, COMMISSION, SALAIRE+COMMISSION FROM EMPLOYES

 * oracle+cx_oracle://stag26:***@51.91.76.248:15440/coursdb
0 rows affected.

[('Berlioz', Decimal('9400'), Decimal('980'), 10380),
 ('Nocella', Decimal('7600'), Decimal('910'), 8510),
 ('Herve', Decimal('6700'), Decimal('1170'), 7870),
 ('Mangeard', Decimal('8200'), Decimal('190'), 8390),
 ('Cazade', Decimal('7200'), Decimal('550'), 7750),
 ('Devie', Decimal('1540'), None, None),
 ('Peacock', Decimal('6100'), Decimal('930'), 7030),
 ('Idesheim', Decimal('7300'), Decimal('600'), 7900),
 ('Rollet', Decimal('5000'), Decimal('570'), 5570),
 ('Silberreiss', Decimal('9200'), Decimal('1100'), 10300),
 ('Weiss', Decimal('6600'), Decimal('1110'), 7710),
 ('Delorgue', Decimal('5900'), Decimal('510'), 6410),
 ('Zonca', Decimal('6700'), Decimal('470'), 7170),
 ('Twardowski', Decimal('9400'), Decimal('1540'), 10940),
 ('Coutou', Decimal('6900'), Decimal('770'), 7670),
 ('King', Decimal('7200'), Decimal('1040'), 8240),
 ('Ragon', Decimal('13000'), Decimal('5980'), 18980),
 ('Dohr', Decimal('8200'), Decimal('200'), 8400),
 ('Maurousset', Decimal('8100'), Decimal('1560'), 9660),
 ('Pouetre', Decimal('2000'), None, None),
 ('Montesinos', Decimal('8700'), Decimal('1130'), 9830),
 ('Aubert', Decimal('5100'), Decimal('750'), 5850),
 ('Thomas', Decimal('7100'), Decimal('1310'), 8410),
 ('Falatik', Decimal('7600'), Decimal('1100'), 8700),
 ('Marielle', Decimal('7100'), Decimal('1550'), 8650),
 ('Leger', Decimal('19000'), Decimal('11150'), 30150),
 ('Marchand', Decimal('6900'), Decimal('1280'), 8180),
 ('Seigne', Decimal('9600'), Decimal('1160'), 10760),
 ('Burst', Decimal('7700'), Decimal('1980'), 9680),
 ('Damas', Decimal('7700'), Decimal('530'), 8230),
 ('Espeche', Decimal('6500'), Decimal('1580'), 8080),
 ('Charles', Decimal('6000'), Decimal('1080'), 7080),
 ('Thimoleon', Decimal('8000'), Decimal('1270'), 9270),
 ('Arrambide', Decimal('5400'), Decimal('190'), 5590),
 ('Ziliox', Decimal('1900'), None, None),
 ('Viry', Decimal('6700'), Decimal('740'), 7440),
 ('Cheutin', Decimal('10000'), Decimal('570'), 10570),
 ('Lombard', Decimal('6400'), Decimal('1350'), 7750),
 ('Tourtel', Decimal('8100'), Decimal('1920'), 10020),
 ('Lampis', Decimal('1300'), None, None),
 ('Regner', Decimal('9300'), Decimal('1380'), 10680),
 ('Teixeira', Decimal('6800'), Decimal('330'), 7130),
 ('Besse', Decimal('9900'), Decimal('940'), 10840),
 ('Destenay', Decimal('9900'), Decimal('790'), 10690),
 ('Letertre', Decimal('5600'), Decimal('1890'), 7490),
 ('Kremser', Decimal('6000'), Decimal('1610'), 7610),
 ('Lamarre', Decimal('7800'), Decimal('200'), 8000),
 ('Cleret', Decimal('7900'), Decimal('720'), 8620),
 ('Poidatz', Decimal('6600'), Decimal('200'), 6800),
 ('Messelier', Decimal('9500'), Decimal('1470'), 10970),
 ('Gardeil', Decimal('7800'), Decimal('1520'), 9320),
 ('Capharsie', Decimal('9400'), Decimal('410'), 9810),
 ('Belin', Decimal('10000'), Decimal('10640'), 20640),
 ('Perny', Decimal('6500'), Decimal('340'), 6840),
 ('Courty', Decimal('9900'), Decimal('1800'), 11700),
 ('Fuller', Decimal('96000'), None, None),
 ('Suyama', Decimal('8400'), Decimal('400'), 8800),
 ('Malejac', Decimal('8700'), Decimal('1130'), 9830),
 ('Blard', Decimal('5900'), Decimal('340'), 6240),
 ('Brasseur', Decimal('147000'), None, None),
 ('Pagani', Decimal('6500'), Decimal('1330'), 7830),
 ('Gerard', Decimal('8200'), Decimal('1800'), 10000),
 ('Poupard', Decimal('1800'), None, None),
 ('Piroddi', Decimal('6700'), Decimal('190'), 6890),
 ('Splingart', Decimal('16000'), Decimal('16480'), 32480),
 ('Buchanan', Decimal('13000'), Decimal('12940'), 25940),
 ('Chaussende', Decimal('6600'), Decimal('1530'), 8130),
 ('Hanriot', Decimal('8300'), Decimal('1700'), 10000),
 ('Maurer', Decimal('1400'), None, None),
 ('Davolio', Decimal('8200'), Decimal('1740'), 9940),
 ('Frederic', Decimal('8100'), Decimal('1870'), 9970),
 ('Callahan', Decimal('1200'), None, None),
 ('Pequignot', Decimal('6200'), Decimal('1820'), 8020),
 ('Duriez', Decimal('9100'), Decimal('420'), 9520),
 ('Chambaud', Decimal('12000'), Decimal('11600'), 23600),
 ('Leverling', Decimal('7400'), Decimal('240'), 7640),
 ('Brunet', Decimal('6600'), Decimal('1400'), 8000),
 ('Cremel', Decimal('6900'), Decimal('910'), 7810),
 ('Giroux', Decimal('150000'), None, None),
 ('Perret', Decimal('9500'), Decimal('520'), 10020),
 ('Jenny', Decimal('9800'), Decimal('150'), 9950),
 ('Mennetrier', Decimal('8700'), Decimal('1970'), 10670),
 ('Michiels', Decimal('5500'), Decimal('40'), 5540),
 ('Valot', Decimal('9200'), Decimal('680'), 9880),
 ('Steiner', Decimal('5400'), Decimal('1310'), 6710),
 ('Etienne', Decimal('2000'), None, None),
 ('Gregoire', Decimal('8000'), Decimal('30'), 8030),
 ('Guillossou', Decimal('5200'), Decimal('470'), 5670),
 ('Lefebvre', Decimal('9200'), Decimal('530'), 9730),
 ('Di Clemente', Decimal('8400'), Decimal('920'), 9320),
 ('Bettan', Decimal('5500'), Decimal('690'), 6190),
 ('Rivat', Decimal('5200'), Decimal('310'), 5510),
 ('Alvarez', Decimal('7200'), Decimal('1010'), 8210),
 ('Jacquot', Decimal('8900'), Decimal('1030'), 9930),
 ('Dodsworth', Decimal('8800'), Decimal('490'), 9290),
 ('Petit', Decimal('6300'), Decimal('20'), 6320),
 ('Canu', Decimal('5800'), Decimal('550'), 6350),
 ('Bazart', Decimal('8900'), Decimal('760'), 9660),
 ('Grangirard', Decimal('1700'), None, None),
 ('Barre', Decimal('8800'), Decimal('1220'), 10020),
 ('Mure', Decimal('8200'), Decimal('1140'), 9340),
 ('Jeandel', Decimal('9200'), Decimal('1150'), 10350),
 ('Aubry', Decimal('9500'), Decimal('1850'), 11350),
 ('Kessler', Decimal('6800'), Decimal('1780'), 8580),
 ('Urbaniak', Decimal('7000'), Decimal('1760'), 8760),
 ('Guerdon', Decimal('1700'), None, None),
 ('Griner', Decimal('8100'), Decimal('980'), 9080),
 ('Bodard', Decimal('5500'), Decimal('720'), 6220),
 ('Maillard', Decimal('6600'), Decimal('1300'), 7900),
 ('Dupouey', Decimal('5500'), Decimal('40'), 5540),
 ('Clement', Decimal('7200'), Decimal('1370'), 8570)]

## COALESCE

In [46]:
%sql \
SELECT NOM, SALAIRE, COMMISSION, SALAIRE+COALESCE(COMMISSION,0) FROM EMPLOYES

 * oracle+cx_oracle://stag26:***@51.91.76.248:15440/coursdb
0 rows affected.

[('Berlioz', Decimal('9400'), Decimal('980'), 10380),
 ('Nocella', Decimal('7600'), Decimal('910'), 8510),
 ('Herve', Decimal('6700'), Decimal('1170'), 7870),
 ('Mangeard', Decimal('8200'), Decimal('190'), 8390),
 ('Cazade', Decimal('7200'), Decimal('550'), 7750),
 ('Devie', Decimal('1540'), None, 1540),
 ('Peacock', Decimal('6100'), Decimal('930'), 7030),
 ('Idesheim', Decimal('7300'), Decimal('600'), 7900),
 ('Rollet', Decimal('5000'), Decimal('570'), 5570),
 ('Silberreiss', Decimal('9200'), Decimal('1100'), 10300),
 ('Weiss', Decimal('6600'), Decimal('1110'), 7710),
 ('Delorgue', Decimal('5900'), Decimal('510'), 6410),
 ('Zonca', Decimal('6700'), Decimal('470'), 7170),
 ('Twardowski', Decimal('9400'), Decimal('1540'), 10940),
 ('Coutou', Decimal('6900'), Decimal('770'), 7670),
 ('King', Decimal('7200'), Decimal('1040'), 8240),
 ('Ragon', Decimal('13000'), Decimal('5980'), 18980),
 ('Dohr', Decimal('8200'), Decimal('200'), 8400),
 ('Maurousset', Decimal('8100'), Decimal('1560'), 9660),
 ('Pouetre', Decimal('2000'), None, 2000),
 ('Montesinos', Decimal('8700'), Decimal('1130'), 9830),
 ('Aubert', Decimal('5100'), Decimal('750'), 5850),
 ('Thomas', Decimal('7100'), Decimal('1310'), 8410),
 ('Falatik', Decimal('7600'), Decimal('1100'), 8700),
 ('Marielle', Decimal('7100'), Decimal('1550'), 8650),
 ('Leger', Decimal('19000'), Decimal('11150'), 30150),
 ('Marchand', Decimal('6900'), Decimal('1280'), 8180),
 ('Seigne', Decimal('9600'), Decimal('1160'), 10760),
 ('Burst', Decimal('7700'), Decimal('1980'), 9680),
 ('Damas', Decimal('7700'), Decimal('530'), 8230),
 ('Espeche', Decimal('6500'), Decimal('1580'), 8080),
 ('Charles', Decimal('6000'), Decimal('1080'), 7080),
 ('Thimoleon', Decimal('8000'), Decimal('1270'), 9270),
 ('Arrambide', Decimal('5400'), Decimal('190'), 5590),
 ('Ziliox', Decimal('1900'), None, 1900),
 ('Viry', Decimal('6700'), Decimal('740'), 7440),
 ('Cheutin', Decimal('10000'), Decimal('570'), 10570),
 ('Lombard', Decimal('6400'), Decimal('1350'), 7750),
 ('Tourtel', Decimal('8100'), Decimal('1920'), 10020),
 ('Lampis', Decimal('1300'), None, 1300),
 ('Regner', Decimal('9300'), Decimal('1380'), 10680),
 ('Teixeira', Decimal('6800'), Decimal('330'), 7130),
 ('Besse', Decimal('9900'), Decimal('940'), 10840),
 ('Destenay', Decimal('9900'), Decimal('790'), 10690),
 ('Letertre', Decimal('5600'), Decimal('1890'), 7490),
 ('Kremser', Decimal('6000'), Decimal('1610'), 7610),
 ('Lamarre', Decimal('7800'), Decimal('200'), 8000),
 ('Cleret', Decimal('7900'), Decimal('720'), 8620),
 ('Poidatz', Decimal('6600'), Decimal('200'), 6800),
 ('Messelier', Decimal('9500'), Decimal('1470'), 10970),
 ('Gardeil', Decimal('7800'), Decimal('1520'), 9320),
 ('Capharsie', Decimal('9400'), Decimal('410'), 9810),
 ('Belin', Decimal('10000'), Decimal('10640'), 20640),
 ('Perny', Decimal('6500'), Decimal('340'), 6840),
 ('Courty', Decimal('9900'), Decimal('1800'), 11700),
 ('Fuller', Decimal('96000'), None, 96000),
 ('Suyama', Decimal('8400'), Decimal('400'), 8800),
 ('Malejac', Decimal('8700'), Decimal('1130'), 9830),
 ('Blard', Decimal('5900'), Decimal('340'), 6240),
 ('Brasseur', Decimal('147000'), None, 147000),
 ('Pagani', Decimal('6500'), Decimal('1330'), 7830),
 ('Gerard', Decimal('8200'), Decimal('1800'), 10000),
 ('Poupard', Decimal('1800'), None, 1800),
 ('Piroddi', Decimal('6700'), Decimal('190'), 6890),
 ('Splingart', Decimal('16000'), Decimal('16480'), 32480),
 ('Buchanan', Decimal('13000'), Decimal('12940'), 25940),
 ('Chaussende', Decimal('6600'), Decimal('1530'), 8130),
 ('Hanriot', Decimal('8300'), Decimal('1700'), 10000),
 ('Maurer', Decimal('1400'), None, 1400),
 ('Davolio', Decimal('8200'), Decimal('1740'), 9940),
 ('Frederic', Decimal('8100'), Decimal('1870'), 9970),
 ('Callahan', Decimal('1200'), None, 1200),
 ('Pequignot', Decimal('6200'), Decimal('1820'), 8020),
 ('Duriez', Decimal('9100'), Decimal('420'), 9520),
 ('Chambaud', Decimal('12000'), Decimal('11600'), 23600),
 ('Leverling', Decimal('7400'), Decimal('240'), 7640),
 ('Brunet', Decimal('6600'), Decimal('1400'), 8000),
 ('Cremel', Decimal('6900'), Decimal('910'), 7810),
 ('Giroux', Decimal('150000'), None, 150000),
 ('Perret', Decimal('9500'), Decimal('520'), 10020),
 ('Jenny', Decimal('9800'), Decimal('150'), 9950),
 ('Mennetrier', Decimal('8700'), Decimal('1970'), 10670),
 ('Michiels', Decimal('5500'), Decimal('40'), 5540),
 ('Valot', Decimal('9200'), Decimal('680'), 9880),
 ('Steiner', Decimal('5400'), Decimal('1310'), 6710),
 ('Etienne', Decimal('2000'), None, 2000),
 ('Gregoire', Decimal('8000'), Decimal('30'), 8030),
 ('Guillossou', Decimal('5200'), Decimal('470'), 5670),
 ('Lefebvre', Decimal('9200'), Decimal('530'), 9730),
 ('Di Clemente', Decimal('8400'), Decimal('920'), 9320),
 ('Bettan', Decimal('5500'), Decimal('690'), 6190),
 ('Rivat', Decimal('5200'), Decimal('310'), 5510),
 ('Alvarez', Decimal('7200'), Decimal('1010'), 8210),
 ('Jacquot', Decimal('8900'), Decimal('1030'), 9930),
 ('Dodsworth', Decimal('8800'), Decimal('490'), 9290),
 ('Petit', Decimal('6300'), Decimal('20'), 6320),
 ('Canu', Decimal('5800'), Decimal('550'), 6350),
 ('Bazart', Decimal('8900'), Decimal('760'), 9660),
 ('Grangirard', Decimal('1700'), None, 1700),
 ('Barre', Decimal('8800'), Decimal('1220'), 10020),
 ('Mure', Decimal('8200'), Decimal('1140'), 9340),
 ('Jeandel', Decimal('9200'), Decimal('1150'), 10350),
 ('Aubry', Decimal('9500'), Decimal('1850'), 11350),
 ('Kessler', Decimal('6800'), Decimal('1780'), 8580),
 ('Urbaniak', Decimal('7000'), Decimal('1760'), 8760),
 ('Guerdon', Decimal('1700'), None, 1700),
 ('Griner', Decimal('8100'), Decimal('980'), 9080),
 ('Bodard', Decimal('5500'), Decimal('720'), 6220),
 ('Maillard', Decimal('6600'), Decimal('1300'), 7900),
 ('Dupouey', Decimal('5500'), Decimal('40'), 5540),
 ('Clement', Decimal('7200'), Decimal('1370'), 8570)]

## NVL

In [30]:
%sql \
SELECT NOM, SALAIRE, COMMISSION, SALAIRE+nvl(COMMISSION,0) FROM EMPLOYES

 * oracle+cx_oracle://stag26:***@51.91.76.248:15440/coursdb
0 rows affected.

[('Berlioz', Decimal('9400'), Decimal('980'), 10380),
 ('Nocella', Decimal('7600'), Decimal('910'), 8510),
 ('Herve', Decimal('6700'), Decimal('1170'), 7870),
 ('Mangeard', Decimal('8200'), Decimal('190'), 8390),
 ('Cazade', Decimal('7200'), Decimal('550'), 7750),
 ('Devie', Decimal('1540'), None, 1540),
 ('Peacock', Decimal('6100'), Decimal('930'), 7030),
 ('Idesheim', Decimal('7300'), Decimal('600'), 7900),
 ('Rollet', Decimal('5000'), Decimal('570'), 5570),
 ('Silberreiss', Decimal('9200'), Decimal('1100'), 10300),
 ('Weiss', Decimal('6600'), Decimal('1110'), 7710),
 ('Delorgue', Decimal('5900'), Decimal('510'), 6410),
 ('Zonca', Decimal('6700'), Decimal('470'), 7170),
 ('Twardowski', Decimal('9400'), Decimal('1540'), 10940),
 ('Coutou', Decimal('6900'), Decimal('770'), 7670),
 ('King', Decimal('7200'), Decimal('1040'), 8240),
 ('Ragon', Decimal('13000'), Decimal('5980'), 18980),
 ('Dohr', Decimal('8200'), Decimal('200'), 8400),
 ('Maurousset', Decimal('8100'), Decimal('1560'), 9660),
 ('Pouetre', Decimal('2000'), None, 2000),
 ('Montesinos', Decimal('8700'), Decimal('1130'), 9830),
 ('Aubert', Decimal('5100'), Decimal('750'), 5850),
 ('Thomas', Decimal('7100'), Decimal('1310'), 8410),
 ('Falatik', Decimal('7600'), Decimal('1100'), 8700),
 ('Marielle', Decimal('7100'), Decimal('1550'), 8650),
 ('Leger', Decimal('19000'), Decimal('11150'), 30150),
 ('Marchand', Decimal('6900'), Decimal('1280'), 8180),
 ('Seigne', Decimal('9600'), Decimal('1160'), 10760),
 ('Burst', Decimal('7700'), Decimal('1980'), 9680),
 ('Damas', Decimal('7700'), Decimal('530'), 8230),
 ('Espeche', Decimal('6500'), Decimal('1580'), 8080),
 ('Charles', Decimal('6000'), Decimal('1080'), 7080),
 ('Thimoleon', Decimal('8000'), Decimal('1270'), 9270),
 ('Arrambide', Decimal('5400'), Decimal('190'), 5590),
 ('Ziliox', Decimal('1900'), None, 1900),
 ('Viry', Decimal('6700'), Decimal('740'), 7440),
 ('Cheutin', Decimal('10000'), Decimal('570'), 10570),
 ('Lombard', Decimal('6400'), Decimal('1350'), 7750),
 ('Tourtel', Decimal('8100'), Decimal('1920'), 10020),
 ('Lampis', Decimal('1300'), None, 1300),
 ('Regner', Decimal('9300'), Decimal('1380'), 10680),
 ('Teixeira', Decimal('6800'), Decimal('330'), 7130),
 ('Besse', Decimal('9900'), Decimal('940'), 10840),
 ('Destenay', Decimal('9900'), Decimal('790'), 10690),
 ('Letertre', Decimal('5600'), Decimal('1890'), 7490),
 ('Kremser', Decimal('6000'), Decimal('1610'), 7610),
 ('Lamarre', Decimal('7800'), Decimal('200'), 8000),
 ('Cleret', Decimal('7900'), Decimal('720'), 8620),
 ('Poidatz', Decimal('6600'), Decimal('200'), 6800),
 ('Messelier', Decimal('9500'), Decimal('1470'), 10970),
 ('Gardeil', Decimal('7800'), Decimal('1520'), 9320),
 ('Capharsie', Decimal('9400'), Decimal('410'), 9810),
 ('Belin', Decimal('10000'), Decimal('10640'), 20640),
 ('Perny', Decimal('6500'), Decimal('340'), 6840),
 ('Courty', Decimal('9900'), Decimal('1800'), 11700),
 ('Fuller', Decimal('96000'), None, 96000),
 ('Suyama', Decimal('8400'), Decimal('400'), 8800),
 ('Malejac', Decimal('8700'), Decimal('1130'), 9830),
 ('Blard', Decimal('5900'), Decimal('340'), 6240),
 ('Brasseur', Decimal('147000'), None, 147000),
 ('Pagani', Decimal('6500'), Decimal('1330'), 7830),
 ('Gerard', Decimal('8200'), Decimal('1800'), 10000),
 ('Poupard', Decimal('1800'), None, 1800),
 ('Piroddi', Decimal('6700'), Decimal('190'), 6890),
 ('Splingart', Decimal('16000'), Decimal('16480'), 32480),
 ('Buchanan', Decimal('13000'), Decimal('12940'), 25940),
 ('Chaussende', Decimal('6600'), Decimal('1530'), 8130),
 ('Hanriot', Decimal('8300'), Decimal('1700'), 10000),
 ('Maurer', Decimal('1400'), None, 1400),
 ('Davolio', Decimal('8200'), Decimal('1740'), 9940),
 ('Frederic', Decimal('8100'), Decimal('1870'), 9970),
 ('Callahan', Decimal('1200'), None, 1200),
 ('Pequignot', Decimal('6200'), Decimal('1820'), 8020),
 ('Duriez', Decimal('9100'), Decimal('420'), 9520),
 ('Chambaud', Decimal('12000'), Decimal('11600'), 23600),
 ('Leverling', Decimal('7400'), Decimal('240'), 7640),
 ('Brunet', Decimal('6600'), Decimal('1400'), 8000),
 ('Cremel', Decimal('6900'), Decimal('910'), 7810),
 ('Giroux', Decimal('150000'), None, 150000),
 ('Perret', Decimal('9500'), Decimal('520'), 10020),
 ('Jenny', Decimal('9800'), Decimal('150'), 9950),
 ('Mennetrier', Decimal('8700'), Decimal('1970'), 10670),
 ('Michiels', Decimal('5500'), Decimal('40'), 5540),
 ('Valot', Decimal('9200'), Decimal('680'), 9880),
 ('Steiner', Decimal('5400'), Decimal('1310'), 6710),
 ('Etienne', Decimal('2000'), None, 2000),
 ('Gregoire', Decimal('8000'), Decimal('30'), 8030),
 ('Guillossou', Decimal('5200'), Decimal('470'), 5670),
 ('Lefebvre', Decimal('9200'), Decimal('530'), 9730),
 ('Di Clemente', Decimal('8400'), Decimal('920'), 9320),
 ('Bettan', Decimal('5500'), Decimal('690'), 6190),
 ('Rivat', Decimal('5200'), Decimal('310'), 5510),
 ('Alvarez', Decimal('7200'), Decimal('1010'), 8210),
 ('Jacquot', Decimal('8900'), Decimal('1030'), 9930),
 ('Dodsworth', Decimal('8800'), Decimal('490'), 9290),
 ('Petit', Decimal('6300'), Decimal('20'), 6320),
 ('Canu', Decimal('5800'), Decimal('550'), 6350),
 ('Bazart', Decimal('8900'), Decimal('760'), 9660),
 ('Grangirard', Decimal('1700'), None, 1700),
 ('Barre', Decimal('8800'), Decimal('1220'), 10020),
 ('Mure', Decimal('8200'), Decimal('1140'), 9340),
 ('Jeandel', Decimal('9200'), Decimal('1150'), 10350),
 ('Aubry', Decimal('9500'), Decimal('1850'), 11350),
 ('Kessler', Decimal('6800'), Decimal('1780'), 8580),
 ('Urbaniak', Decimal('7000'), Decimal('1760'), 8760),
 ('Guerdon', Decimal('1700'), None, 1700),
 ('Griner', Decimal('8100'), Decimal('980'), 9080),
 ('Bodard', Decimal('5500'), Decimal('720'), 6220),
 ('Maillard', Decimal('6600'), Decimal('1300'), 7900),
 ('Dupouey', Decimal('5500'), Decimal('40'), 5540),
 ('Clement', Decimal('7200'), Decimal('1370'), 8570)]

In [31]:
%sql \
SELECT SOCIETE, NVL(FAX, 'Non affecté') FROM CLIENTS

 * oracle+cx_oracle://stag26:***@51.91.76.248:15440/coursdb
0 rows affected.

[('Consolidated Holdings', '(71) 555-9199'),
 ('Drachenblut Delikatessen', '0241-059428'),
 ('Du monde entier', '02.40.67.89.89'),
 ('Eastern Connection', '(71) 555-3373'),
 ('Ernst Handel', '7675-3426'),
 ('Familia Arquibaldo', 'Non affecté'),
 ('FISSA Fabrica Inter. Salchichas S.A.', '(91) 555 55 93'),
 ('Folies gourmandes', '03.20.16.10.17'),
 ('Folk och fä HB', 'Non affecté'),
 ('Frankenversand', '089-0877451'),
 ('France restauration', '02.40.32.21.20'),
 ('Franchi S.p.A.', '011-4988261'),
 ('Furia Bacalhau e Frutos do Mar', '(1) 354-2535'),
 ('Galería del gastrónomo', '(93) 203 4561'),
 ('Godos Cocina Típica', 'Non affecté'),
 ('Gourmet Lanchonetes', 'Non affecté'),
 ('Great Lakes Food Market', 'Non affecté'),
 ('GROSELLA-Restaurante', '(2) 283-3397'),
 ('Hanari Carnes', '(21) 555-8765'),
 ('HILARIÓN-Abastos', '(5) 555-1948'),
 ('Hungry Coyote Import Store', '(503) 555-2376'),
 ('Hungry Owl All-Night Grocers', '2967 3333'),
 ('Island Trading', 'Non affecté'),
 ('Königlich Essen', 'Non affecté'),
 ("La corne d'abondance", '01.30.59.85.11'),
 ("La maison d'Asie", '05.61.77.61.11'),
 ('Laughing Bacchus Wine Cellars', '(604) 555-7293'),
 ('Lazy K Kountry Store', '(509) 555-6221'),
 ('Lehmanns Marktstand', '069-0245874'),
 ("Let's Stop N Shop", 'Non affecté'),
 ('LILA-Supermercado', '(9) 331-7256'),
 ('LINO-Delicateses', '(8) 34-93-93'),
 ('Lonesome Pine Restaurant', '(503) 555-9646'),
 ('Magazzini Alimentari Riuniti', '035-640231'),
 ('Maison Dewey', '(02) 201 24 68'),
 ('Mère Paillarde', '(514) 555-8055'),
 ('Morgenstern Gesundkost', 'Non affecté'),
 ('North/South', '(71) 555-2530'),
 ('Océano Atlántico Ltda.', '(1) 135-5535'),
 ('Old World Delicatessen', '(907) 555-2880'),
 ('Ottilies Käseladen', '0221-0765721'),
 ('Paris spécialités', '01.42.34.22.77'),
 ('Pericles Comidas clásicas', '(5) 545-3745'),
 ('Piccolo und mehr', '6562-9723'),
 ('Princesa Isabel Vinhos', 'Non affecté'),
 ('Que Delícia', '(21) 555-4545'),
 ('Queen Cozinha', 'Non affecté'),
 ('QUICK-Stop', 'Non affecté'),
 ('Rancho grande', '(1) 123-5556'),
 ('Rattlesnake Canyon Grocery', '(505) 555-3620'),
 ('Reggiani Caseifici', '0522-556722'),
 ('Ricardo Adocicados', 'Non affecté'),
 ('Richter Supermarkt', 'Non affecté'),
 ('Romero y tomillo', '(91) 745 6210'),
 ('Santé Gourmet', '07-98 92 47'),
 ('Save-a-lot Markets', 'Non affecté'),
 ('Seven Seas Imports', '(71) 555-5646'),
 ('Simons bistro', '31 13 35 57'),
 ('Spécialités du monde', '01.47.55.60.20'),
 ('Split Rail Beer  Ale', '(307) 555-6525'),
 ('Suprêmes délices', '(071) 23 67 22 21'),
 ('The Big Cheese', 'Non affecté'),
 ('The Cracker Box', '(406) 555-8083'),
 ('Toms Spezialitäten', '0251-035695'),
 ('Tortuga Restaurante', 'Non affecté'),
 ('Tradição Hipermercados', '(11) 555-2168'),
 ("Trail's Head Gourmet Provisioners", '(206) 555-2174'),
 ('Vaffeljernet', '86 22 33 44'),
 ('Victuailles en stock', '04.78.32.54.87'),
 ('Vins et alcools Chevalier', '03.26.47.15.11'),
 ('Die Wandernde Kuh', '0711-035428'),
 ('Wartian Herkku', '981-443655'),
 ('Wellington Importadora', 'Non affecté'),
 ('White Clover Markets', '(206) 555-4115'),
 ('Wilman Kala', '90-224 8858'),
 ('Wolski  Zajazd', '(26) 642-7012'),
 ('Alfreds Futterkiste', '030-0076545'),
 ('Ana Trujillo Emparedados y helados', '(5) 555-3745'),
 ('Antonio Moreno Taquería', 'Non affecté'),
 ('Around the Horn', '(71) 555-6750'),
 ('Berglunds snabbköp', '0921-12 34 67'),
 ('Blauer See Delikatessen', '0621-08924'),
 ('Blondel père et fils', '03.88.60.15.32'),
 ('Bólido Comidas preparadas', '(91) 555 91 99'),
 ("Bon app'", '04.91.24.45.41'),
 ('Bottom-Dollar Markets', '(604) 555-3745'),
 ("B's Beverages", 'Non affecté'),
 ('Cactus Comidas para llevar', '(1) 135-4892'),
 ('Centro comercial Moctezuma', '(5) 555-7293'),
 ('Chop-suey Chinese', 'Non affecté'),
 ('Comércio Mineiro', 'Non affecté')]

## NVL2

In [32]:
%sql \
SELECT NOM, SALAIRE, COMMISSION,\
       NVL2( COMMISSION, SALAIRE+COMMISSION, SALAIRE) R \
FROM EMPLOYES

 * oracle+cx_oracle://stag26:***@51.91.76.248:15440/coursdb
0 rows affected.

[('Berlioz', Decimal('9400'), Decimal('980'), 10380),
 ('Nocella', Decimal('7600'), Decimal('910'), 8510),
 ('Herve', Decimal('6700'), Decimal('1170'), 7870),
 ('Mangeard', Decimal('8200'), Decimal('190'), 8390),
 ('Cazade', Decimal('7200'), Decimal('550'), 7750),
 ('Devie', Decimal('1540'), None, 1540),
 ('Peacock', Decimal('6100'), Decimal('930'), 7030),
 ('Idesheim', Decimal('7300'), Decimal('600'), 7900),
 ('Rollet', Decimal('5000'), Decimal('570'), 5570),
 ('Silberreiss', Decimal('9200'), Decimal('1100'), 10300),
 ('Weiss', Decimal('6600'), Decimal('1110'), 7710),
 ('Delorgue', Decimal('5900'), Decimal('510'), 6410),
 ('Zonca', Decimal('6700'), Decimal('470'), 7170),
 ('Twardowski', Decimal('9400'), Decimal('1540'), 10940),
 ('Coutou', Decimal('6900'), Decimal('770'), 7670),
 ('King', Decimal('7200'), Decimal('1040'), 8240),
 ('Ragon', Decimal('13000'), Decimal('5980'), 18980),
 ('Dohr', Decimal('8200'), Decimal('200'), 8400),
 ('Maurousset', Decimal('8100'), Decimal('1560'), 9660),
 ('Pouetre', Decimal('2000'), None, 2000),
 ('Montesinos', Decimal('8700'), Decimal('1130'), 9830),
 ('Aubert', Decimal('5100'), Decimal('750'), 5850),
 ('Thomas', Decimal('7100'), Decimal('1310'), 8410),
 ('Falatik', Decimal('7600'), Decimal('1100'), 8700),
 ('Marielle', Decimal('7100'), Decimal('1550'), 8650),
 ('Leger', Decimal('19000'), Decimal('11150'), 30150),
 ('Marchand', Decimal('6900'), Decimal('1280'), 8180),
 ('Seigne', Decimal('9600'), Decimal('1160'), 10760),
 ('Burst', Decimal('7700'), Decimal('1980'), 9680),
 ('Damas', Decimal('7700'), Decimal('530'), 8230),
 ('Espeche', Decimal('6500'), Decimal('1580'), 8080),
 ('Charles', Decimal('6000'), Decimal('1080'), 7080),
 ('Thimoleon', Decimal('8000'), Decimal('1270'), 9270),
 ('Arrambide', Decimal('5400'), Decimal('190'), 5590),
 ('Ziliox', Decimal('1900'), None, 1900),
 ('Viry', Decimal('6700'), Decimal('740'), 7440),
 ('Cheutin', Decimal('10000'), Decimal('570'), 10570),
 ('Lombard', Decimal('6400'), Decimal('1350'), 7750),
 ('Tourtel', Decimal('8100'), Decimal('1920'), 10020),
 ('Lampis', Decimal('1300'), None, 1300),
 ('Regner', Decimal('9300'), Decimal('1380'), 10680),
 ('Teixeira', Decimal('6800'), Decimal('330'), 7130),
 ('Besse', Decimal('9900'), Decimal('940'), 10840),
 ('Destenay', Decimal('9900'), Decimal('790'), 10690),
 ('Letertre', Decimal('5600'), Decimal('1890'), 7490),
 ('Kremser', Decimal('6000'), Decimal('1610'), 7610),
 ('Lamarre', Decimal('7800'), Decimal('200'), 8000),
 ('Cleret', Decimal('7900'), Decimal('720'), 8620),
 ('Poidatz', Decimal('6600'), Decimal('200'), 6800),
 ('Messelier', Decimal('9500'), Decimal('1470'), 10970),
 ('Gardeil', Decimal('7800'), Decimal('1520'), 9320),
 ('Capharsie', Decimal('9400'), Decimal('410'), 9810),
 ('Belin', Decimal('10000'), Decimal('10640'), 20640),
 ('Perny', Decimal('6500'), Decimal('340'), 6840),
 ('Courty', Decimal('9900'), Decimal('1800'), 11700),
 ('Fuller', Decimal('96000'), None, 96000),
 ('Suyama', Decimal('8400'), Decimal('400'), 8800),
 ('Malejac', Decimal('8700'), Decimal('1130'), 9830),
 ('Blard', Decimal('5900'), Decimal('340'), 6240),
 ('Brasseur', Decimal('147000'), None, 147000),
 ('Pagani', Decimal('6500'), Decimal('1330'), 7830),
 ('Gerard', Decimal('8200'), Decimal('1800'), 10000),
 ('Poupard', Decimal('1800'), None, 1800),
 ('Piroddi', Decimal('6700'), Decimal('190'), 6890),
 ('Splingart', Decimal('16000'), Decimal('16480'), 32480),
 ('Buchanan', Decimal('13000'), Decimal('12940'), 25940),
 ('Chaussende', Decimal('6600'), Decimal('1530'), 8130),
 ('Hanriot', Decimal('8300'), Decimal('1700'), 10000),
 ('Maurer', Decimal('1400'), None, 1400),
 ('Davolio', Decimal('8200'), Decimal('1740'), 9940),
 ('Frederic', Decimal('8100'), Decimal('1870'), 9970),
 ('Callahan', Decimal('1200'), None, 1200),
 ('Pequignot', Decimal('6200'), Decimal('1820'), 8020),
 ('Duriez', Decimal('9100'), Decimal('420'), 9520),
 ('Chambaud', Decimal('12000'), Decimal('11600'), 23600),
 ('Leverling', Decimal('7400'), Decimal('240'), 7640),
 ('Brunet', Decimal('6600'), Decimal('1400'), 8000),
 ('Cremel', Decimal('6900'), Decimal('910'), 7810),
 ('Giroux', Decimal('150000'), None, 150000),
 ('Perret', Decimal('9500'), Decimal('520'), 10020),
 ('Jenny', Decimal('9800'), Decimal('150'), 9950),
 ('Mennetrier', Decimal('8700'), Decimal('1970'), 10670),
 ('Michiels', Decimal('5500'), Decimal('40'), 5540),
 ('Valot', Decimal('9200'), Decimal('680'), 9880),
 ('Steiner', Decimal('5400'), Decimal('1310'), 6710),
 ('Etienne', Decimal('2000'), None, 2000),
 ('Gregoire', Decimal('8000'), Decimal('30'), 8030),
 ('Guillossou', Decimal('5200'), Decimal('470'), 5670),
 ('Lefebvre', Decimal('9200'), Decimal('530'), 9730),
 ('Di Clemente', Decimal('8400'), Decimal('920'), 9320),
 ('Bettan', Decimal('5500'), Decimal('690'), 6190),
 ('Rivat', Decimal('5200'), Decimal('310'), 5510),
 ('Alvarez', Decimal('7200'), Decimal('1010'), 8210),
 ('Jacquot', Decimal('8900'), Decimal('1030'), 9930),
 ('Dodsworth', Decimal('8800'), Decimal('490'), 9290),
 ('Petit', Decimal('6300'), Decimal('20'), 6320),
 ('Canu', Decimal('5800'), Decimal('550'), 6350),
 ('Bazart', Decimal('8900'), Decimal('760'), 9660),
 ('Grangirard', Decimal('1700'), None, 1700),
 ('Barre', Decimal('8800'), Decimal('1220'), 10020),
 ('Mure', Decimal('8200'), Decimal('1140'), 9340),
 ('Jeandel', Decimal('9200'), Decimal('1150'), 10350),
 ('Aubry', Decimal('9500'), Decimal('1850'), 11350),
 ('Kessler', Decimal('6800'), Decimal('1780'), 8580),
 ('Urbaniak', Decimal('7000'), Decimal('1760'), 8760),
 ('Guerdon', Decimal('1700'), None, 1700),
 ('Griner', Decimal('8100'), Decimal('980'), 9080),
 ('Bodard', Decimal('5500'), Decimal('720'), 6220),
 ('Maillard', Decimal('6600'), Decimal('1300'), 7900),
 ('Dupouey', Decimal('5500'), Decimal('40'), 5540),
 ('Clement', Decimal('7200'), Decimal('1370'), 8570)]

# Tri du résultat d'une requête

>> **SELECT [ALL | DISTINCT]{*,[EXPRESSION1 [AS] ALIAS1[,...]}<br>
>> FROM NOM_TABLE<br>
>> ORDER BY <br>
>> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[NOM_COLONNE1|ALIAS1|POSITION1|EXPRESSION1][ASC|DESC] [NULLS {FIRST|LAST}],<br>
>> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[NOM_COLONNE2|ALIAS2|POSITION2|EXPRESSION2][ASC|DESC] [NULLS {FIRST|LAST}]**<br>

In [33]:
%sql \
SELECT NOM, PRENOM, FONCTION FROM EMPLOYES ORDER BY NOM

 * oracle+cx_oracle://stag26:***@51.91.76.248:15440/coursdb
0 rows affected.

[('Alvarez', 'Marcel', 'Représentant(e)'),
 ('Arrambide', 'Jean Pierre', 'Représentant(e)'),
 ('Aubert', 'Maria', 'Représentant(e)'),
 ('Aubry', 'Jean-Claude', 'Représentant(e)'),
 ('Barre', 'Jean-Paul', 'Représentant(e)'),
 ('Bazart', 'Régis', 'Représentant(e)'),
 ('Belin', 'Chantal', 'Chef des ventes'),
 ('Berlioz', 'Jacques', 'Représentant(e)'),
 ('Besse', 'José', 'Représentant(e)'),
 ('Bettan', 'Henri-Michel', 'Représentant(e)'),
 ('Blard', 'Jean-Benoît', 'Représentant(e)'),
 ('Bodard', 'René', 'Représentant(e)'),
 ('Brasseur', 'Hervé', 'Vice-Président'),
 ('Brunet', 'Jean-Luc', 'Représentant(e)'),
 ('Buchanan', 'Steven', 'Chef des ventes'),
 ('Burst', 'Jean-Yves', 'Représentant(e)'),
 ('Callahan', 'Laura', 'Assistante commerciale'),
 ('Canu', 'Christian', 'Représentant(e)'),
 ('Capharsie', 'Gérard', 'Représentant(e)'),
 ('Cazade', 'Anne-Claire', 'Représentant(e)'),
 ('Chambaud', 'Axelle', 'Chef des ventes'),
 ('Charles', 'Philippe', 'Représentant(e)'),
 ('Chaussende', 'Maurice', 'Représentant(e)'),
 ('Cheutin', 'Corinne', 'Représentant(e)'),
 ('Clement', 'Valérie', 'Représentant(e)'),
 ('Cleret', 'Doris', 'Représentant(e)'),
 ('Courty', 'Jean-Louis', 'Représentant(e)'),
 ('Coutou', 'Myriam', 'Représentant(e)'),
 ('Cremel', 'Brigitte', 'Représentant(e)'),
 ('Damas', 'Lydiane', 'Représentant(e)'),
 ('Davolio', 'Nancy', 'Représentant(e)'),
 ('Delorgue', 'Jean', 'Représentant(e)'),
 ('Destenay', 'Agnès', 'Représentant(e)'),
 ('Devie', 'Thérèse', 'Assistante commerciale'),
 ('Di Clemente', 'Luc', 'Représentant(e)'),
 ('Dodsworth', 'Anne', 'Représentant(e)'),
 ('Dohr', 'Sylvie', 'Représentant(e)'),
 ('Dupouey', 'Pierre', 'Représentant(e)'),
 ('Duriez', 'Maurice', 'Représentant(e)'),
 ('Espeche', 'Eric', 'Représentant(e)'),
 ('Etienne', 'Brigitte', 'Assistante commerciale'),
 ('Falatik', 'Bernard', 'Représentant(e)'),
 ('Frederic', 'Jean Marie', 'Représentant(e)'),
 ('Fuller', 'Andrew', 'Vice-Président'),
 ('Gardeil', 'Henri', 'Représentant(e)'),
 ('Gerard', 'Sylvie', 'Représentant(e)'),
 ('Giroux', 'Jean-Claude', 'Président'),
 ('Grangirard', 'Patricia', 'Assistante commerciale'),
 ('Gregoire', 'Renée', 'Représentant(e)'),
 ('Griner', 'Florence', 'Représentant(e)'),
 ('Guerdon', 'Béatrice', 'Assistante commerciale'),
 ('Guillossou', 'Nadine', 'Représentant(e)'),
 ('Hanriot', 'Catherine', 'Représentant(e)'),
 ('Herve', 'Didier', 'Représentant(e)'),
 ('Idesheim', 'Annick', 'Représentant(e)'),
 ('Jacquot', 'Philippe', 'Représentant(e)'),
 ('Jeandel', 'Véronique', 'Représentant(e)'),
 ('Jenny', 'Michel', 'Représentant(e)'),
 ('Kessler', 'Marc', 'Représentant(e)'),
 ('King', 'Robert', 'Représentant(e)'),
 ('Kremser', 'Arnaud', 'Représentant(e)'),
 ('Lamarre', 'Eric', 'Représentant(e)'),
 ('Lampis', 'Gabrielle', 'Assistante commerciale'),
 ('Lefebvre', 'Michel', 'Représentant(e)'),
 ('Leger', 'Pierre', 'Chef des ventes'),
 ('Letertre', 'Sylvie', 'Représentant(e)'),
 ('Leverling', 'Janet', 'Représentant(e)'),
 ('Lombard', 'Christiane', 'Représentant(e)'),
 ('Maillard', 'Corinne', 'Représentant(e)'),
 ('Malejac', 'Yannick', 'Représentant(e)'),
 ('Mangeard', 'Jocelyne', 'Représentant(e)'),
 ('Marchand', 'Dominique', 'Représentant(e)'),
 ('Marielle', 'Michel', 'Représentant(e)'),
 ('Maurer', 'Véronique', 'Assistante commerciale'),
 ('Maurousset', 'James', 'Représentant(e)'),
 ('Mennetrier', 'Alexandra', 'Représentant(e)'),
 ('Messelier', 'Philippe', 'Représentant(e)'),
 ('Michiels', 'François', 'Représentant(e)'),
 ('Montesinos', 'Aline', 'Représentant(e)'),
 ('Mure', 'Guy', 'Représentant(e)'),
 ('Nocella', 'Guy', 'Représentant(e)'),
 ('Pagani', 'Hector', 'Représentant(e)'),
 ('Peacock', 'Margaret', 'Représentant(e)'),
 ('Pequignot', 'Guy', 'Représentant(e)'),
 ('Perny', 'Sylvie', 'Représentant(e)'),
 ('Perret', 'Laurence', 'Représentant(e)'),
 ('Petit', 'Michel', 'Représentant(e)'),
 ('Piroddi', 'Nathalie', 'Représentant(e)'),
 ('Poidatz', 'Benoît', 'Représentant(e)'),
 ('Pouetre', 'Camille-Hélène', 'Assistante commerciale'),
 ('Poupard', 'Claudette', 'Assistante commerciale'),
 ('Ragon', 'André', 'Chef des ventes'),
 ('Regner', 'Charles', 'Représentant(e)'),
 ('Rivat', 'Jean-Louis', 'Représentant(e)'),
 ('Rollet', 'Philippe', 'Représentant(e)'),
 ('Seigne', 'Marie-Pierre', 'Représentant(e)'),
 ('Silberreiss', 'Albert', 'Représentant(e)'),
 ('Splingart', 'Lydia', 'Chef des ventes'),
 ('Steiner', 'Jean', 'Représentant(e)'),
 ('Suyama', 'Michael', 'Représentant(e)'),
 ('Teixeira', 'Claudia', 'Représentant(e)'),
 ('Thimoleon', 'Georges', 'Représentant(e)'),
 ('Thomas', 'Patricia', 'Représentant(e)'),
 ('Tourtel', 'Nicole', 'Représentant(e)'),
 ('Twardowski', 'Colette', 'Représentant(e)'),
 ('Urbaniak', 'Isabelle', 'Représentant(e)'),
 ('Valot', 'Alain', 'Représentant(e)'),
 ('Viry', 'Yvan', 'Représentant(e)'),
 ('Weiss', 'Sylvie', 'Représentant(e)'),
 ('Ziliox', 'Francoise', 'Assistante commerciale'),
 ('Zonca', 'Virginie', 'Représentant(e)')]

In [34]:
%sql \
SELECT NOM||' '||PRENOM "Employé", FONCTION \
FROM EMPLOYES \
ORDER BY "Employé" ASC

 * oracle+cx_oracle://stag26:***@51.91.76.248:15440/coursdb
0 rows affected.

[('Alvarez Marcel', 'Représentant(e)'),
 ('Arrambide Jean Pierre', 'Représentant(e)'),
 ('Aubert Maria', 'Représentant(e)'),
 ('Aubry Jean-Claude', 'Représentant(e)'),
 ('Barre Jean-Paul', 'Représentant(e)'),
 ('Bazart Régis', 'Représentant(e)'),
 ('Belin Chantal', 'Chef des ventes'),
 ('Berlioz Jacques', 'Représentant(e)'),
 ('Besse José', 'Représentant(e)'),
 ('Bettan Henri-Michel', 'Représentant(e)'),
 ('Blard Jean-Benoît', 'Représentant(e)'),
 ('Bodard René', 'Représentant(e)'),
 ('Brasseur Hervé', 'Vice-Président'),
 ('Brunet Jean-Luc', 'Représentant(e)'),
 ('Buchanan Steven', 'Chef des ventes'),
 ('Burst Jean-Yves', 'Représentant(e)'),
 ('Callahan Laura', 'Assistante commerciale'),
 ('Canu Christian', 'Représentant(e)'),
 ('Capharsie Gérard', 'Représentant(e)'),
 ('Cazade Anne-Claire', 'Représentant(e)'),
 ('Chambaud Axelle', 'Chef des ventes'),
 ('Charles Philippe', 'Représentant(e)'),
 ('Chaussende Maurice', 'Représentant(e)'),
 ('Cheutin Corinne', 'Représentant(e)'),
 ('Clement Valérie', 'Représentant(e)'),
 ('Cleret Doris', 'Représentant(e)'),
 ('Courty Jean-Louis', 'Représentant(e)'),
 ('Coutou Myriam', 'Représentant(e)'),
 ('Cremel Brigitte', 'Représentant(e)'),
 ('Damas Lydiane', 'Représentant(e)'),
 ('Davolio Nancy', 'Représentant(e)'),
 ('Delorgue Jean', 'Représentant(e)'),
 ('Destenay Agnès', 'Représentant(e)'),
 ('Devie Thérèse', 'Assistante commerciale'),
 ('Di Clemente Luc', 'Représentant(e)'),
 ('Dodsworth Anne', 'Représentant(e)'),
 ('Dohr Sylvie', 'Représentant(e)'),
 ('Dupouey Pierre', 'Représentant(e)'),
 ('Duriez Maurice', 'Représentant(e)'),
 ('Espeche Eric', 'Représentant(e)'),
 ('Etienne Brigitte', 'Assistante commerciale'),
 ('Falatik Bernard', 'Représentant(e)'),
 ('Frederic Jean Marie', 'Représentant(e)'),
 ('Fuller Andrew', 'Vice-Président'),
 ('Gardeil Henri', 'Représentant(e)'),
 ('Gerard Sylvie', 'Représentant(e)'),
 ('Giroux Jean-Claude', 'Président'),
 ('Grangirard Patricia', 'Assistante commerciale'),
 ('Gregoire Renée', 'Représentant(e)'),
 ('Griner Florence', 'Représentant(e)'),
 ('Guerdon Béatrice', 'Assistante commerciale'),
 ('Guillossou Nadine', 'Représentant(e)'),
 ('Hanriot Catherine', 'Représentant(e)'),
 ('Herve Didier', 'Représentant(e)'),
 ('Idesheim Annick', 'Représentant(e)'),
 ('Jacquot Philippe', 'Représentant(e)'),
 ('Jeandel Véronique', 'Représentant(e)'),
 ('Jenny Michel', 'Représentant(e)'),
 ('Kessler Marc', 'Représentant(e)'),
 ('King Robert', 'Représentant(e)'),
 ('Kremser Arnaud', 'Représentant(e)'),
 ('Lamarre Eric', 'Représentant(e)'),
 ('Lampis Gabrielle', 'Assistante commerciale'),
 ('Lefebvre Michel', 'Représentant(e)'),
 ('Leger Pierre', 'Chef des ventes'),
 ('Letertre Sylvie', 'Représentant(e)'),
 ('Leverling Janet', 'Représentant(e)'),
 ('Lombard Christiane', 'Représentant(e)'),
 ('Maillard Corinne', 'Représentant(e)'),
 ('Malejac Yannick', 'Représentant(e)'),
 ('Mangeard Jocelyne', 'Représentant(e)'),
 ('Marchand Dominique', 'Représentant(e)'),
 ('Marielle Michel', 'Représentant(e)'),
 ('Maurer Véronique', 'Assistante commerciale'),
 ('Maurousset James', 'Représentant(e)'),
 ('Mennetrier Alexandra', 'Représentant(e)'),
 ('Messelier Philippe', 'Représentant(e)'),
 ('Michiels François', 'Représentant(e)'),
 ('Montesinos Aline', 'Représentant(e)'),
 ('Mure Guy', 'Représentant(e)'),
 ('Nocella Guy', 'Représentant(e)'),
 ('Pagani Hector', 'Représentant(e)'),
 ('Peacock Margaret', 'Représentant(e)'),
 ('Pequignot Guy', 'Représentant(e)'),
 ('Perny Sylvie', 'Représentant(e)'),
 ('Perret Laurence', 'Représentant(e)'),
 ('Petit Michel', 'Représentant(e)'),
 ('Piroddi Nathalie', 'Représentant(e)'),
 ('Poidatz Benoît', 'Représentant(e)'),
 ('Pouetre Camille-Hélène', 'Assistante commerciale'),
 ('Poupard Claudette', 'Assistante commerciale'),
 ('Ragon André', 'Chef des ventes'),
 ('Regner Charles', 'Représentant(e)'),
 ('Rivat Jean-Louis', 'Représentant(e)'),
 ('Rollet Philippe', 'Représentant(e)'),
 ('Seigne Marie-Pierre', 'Représentant(e)'),
 ('Silberreiss Albert', 'Représentant(e)'),
 ('Splingart Lydia', 'Chef des ventes'),
 ('Steiner Jean', 'Représentant(e)'),
 ('Suyama Michael', 'Représentant(e)'),
 ('Teixeira Claudia', 'Représentant(e)'),
 ('Thimoleon Georges', 'Représentant(e)'),
 ('Thomas Patricia', 'Représentant(e)'),
 ('Tourtel Nicole', 'Représentant(e)'),
 ('Twardowski Colette', 'Représentant(e)'),
 ('Urbaniak Isabelle', 'Représentant(e)'),
 ('Valot Alain', 'Représentant(e)'),
 ('Viry Yvan', 'Représentant(e)'),
 ('Weiss Sylvie', 'Représentant(e)'),
 ('Ziliox Francoise', 'Assistante commerciale'),
 ('Zonca Virginie', 'Représentant(e)')]

Le tri se fait d'abord selon le premier critère spécifié dans la clause « **ORDER BY** », puis les lignes ayant la même valeur pour le premier critère sont triées selon le deuxième critère de la clause « **ORDER BY** », etc.

In [35]:
%sql \
SELECT NOM_PRODUIT, NO_FOURNISSEUR, CODE_CATEGORIE \
FROM PRODUITS\
ORDER BY NO_FOURNISSEUR, CODE_CATEGORIE DESC

 * oracle+cx_oracle://stag26:***@51.91.76.248:15440/coursdb
0 rows affected.

[('Aniseed Syrup', 1, 2),
 ('Chai', 1, 1),
 ('Chang', 1, 1),
 ('Cherry Pie Filling', 2, 9),
 ('Amandes', 2, 7),
 ('Brownie Mix', 2, 3),
 ("Chef Anton's Gumbo Mix", 2, 2),
 ('Louisiana Hot Spiced Okra', 2, 2),
 ("Chef Anton's Cajun Seasoning", 2, 2),
 ('Louisiana Fiery Hot Pepper Sauce', 2, 2),
 ("Uncle Bob's Organic Dried Pears", 3, 7),
 ('Northwoods Cranberry Sauce', 3, 2),
 ("Grandma's Boysenberry Spread", 3, 2),
 ('Corn', 4, 9),
 ('Ikura', 4, 8),
 ('Longlife Tofu', 4, 7),
 ('Long Grain Rice', 4, 7),
 ('Mishi Kobe Niku', 4, 6),
 ('Scones', 4, 3),
 ('Mustard', 4, 2),
 ('Green Beans', 5, 9),
 ('Peas', 5, 9),
 ('Walnuts', 5, 7),
 ('Queso Cabrales', 5, 4),
 ('Queso Manchego La Pastora', 5, 4),
 ('Peaches', 6, 9),
 ('Konbu', 6, 8),
 ('Tofu', 6, 7),
 ('Long Grain Rice - Gnocchi', 6, 5),
 ('Les Comptoirs  - Olive Oil', 6, 2),
 ('Genen Shouyu', 6, 2),
 ('Carnarvon Tigers', 7, 8),
 ('Alice Mutton', 7, 6),
 ('Chocolate Biscuits Mix', 7, 3),
 ('Pavlova', 7, 3),
 ('Vegie-spread', 7, 2),
 ('Outback Lager', 7, 1),
 ('Dried Plums', 8, 7),
 ("Sir Rodney's Marmalade", 8, 3),
 ('Scottish Longbreads', 8, 3),
 ('Teatime Chocolate Biscuits', 8, 3),
 ("Sir Rodney's Scones", 8, 3),
 ('Tunnbröd', 9, 5),
 ("Gustaf's Knäckebröd", 9, 5),
 ('Guaraná Fantástica', 10, 1),
 ('Granola', 11, 5),
 ('Schoggi Schokolade', 11, 3),
 ('NuNuCa Nuß-Nougat-Creme', 11, 3),
 ('Gumbär Gummibärchen', 11, 3),
 ('Rössle Sauerkraut', 12, 7),
 ('Thüringer Rostbratwurst', 12, 6),
 ('Wimmers gute Semmelknödel', 12, 5),
 ('Original Frankfurter grüne Soße', 12, 2),
 ('Rhönbräu Klosterbier', 12, 1),
 ('Fruit Cocktail', 13, 9),
 ('Nord-Ost Matjeshering', 13, 8),
 ('Vegetable Soup', 13, 2),
 ('Smoked Salmon', 14, 10),
 ('Ravioli', 14, 5),
 ('Gorgonzola Telino', 14, 4),
 ('Mascarpone Fabioli', 14, 4),
 ('Mozzarella di Giovanni', 14, 4),
 ('Clam Chowder', 14, 2),
 ('Hot Pepper Sauce', 14, 2),
 ('Green Tea', 14, 1),
 ('Tea', 14, 1),
 ('Gudbrandsdalsost', 15, 4),
 ('Fløtemysost', 15, 4),
 ('Geitost', 15, 4),
 ('Tomato Sauce', 16, 2),
 ('Chicken Soup', 16, 2),
 ('Sasquatch Ale', 16, 1),
 ('Steeleye Stout', 16, 1),
 ('Laughing Lumberjack Lager', 16, 1),
 ('Coffee', 16, 1),
 ('Inlagd Sill', 17, 8),
 ('Gravad lax', 17, 8),
 ('Röd Kaviar', 17, 8),
 ('Syrup', 17, 2),
 ('Hot Cereal', 18, 5),
 ('Mozzarella', 18, 4),
 ('Côte de Blaye', 18, 1),
 ('Chartreuse verte', 18, 1),
 ('Beer', 18, 1),
 ('Crab Meat', 19, 10),
 ("Jack's New England Clam Chowder", 19, 8),
 ('Boston Crab Meat', 19, 8),
 ('Singaporean Hokkien Fried Mee', 20, 5),
 ('Cake Mix', 20, 3),
 ('Gula Malacca', 20, 2),
 ('Ipoh Coffee', 20, 1),
 ('Spegesild', 21, 8),
 ('Røgede sild', 21, 8),
 ('Dried Apples', 21, 7),
 ('Dried Pears', 21, 7),
 ('Zaanse koeken', 22, 3),
 ('Chocolade', 22, 3),
 ('Potato Chips', 23, 7),
 ('Maxilaku', 23, 3),
 ('Valkoinen suklaa', 23, 3),
 ('Lakkalikööri', 23, 1),
 ('Marmalade', 24, 9),
 ('Manjimup Dried Apples', 24, 7),
 ('Perth Pasties', 24, 6),
 ('Filo Mix', 24, 5),
 ('Pears', 25, 9),
 ('Tourtière', 25, 6),
 ('Pâté chinois', 25, 6),
 ('Boysenberry Spread', 26, 9),
 ('Ravioli Angelo', 26, 5),
 ('Gnocchi di nonna Alice', 26, 5),
 ('Curry Sauce', 26, 2),
 ('Tuna Fish', 27, 10),
 ('Pineapple', 27, 9),
 ('Escargots de Bourgogne', 27, 8),
 ('Cajun Seasoning', 27, 2),
 ('Raclette Courdavault', 28, 4),
 ('Camembert Pierrot', 28, 4),
 ('Tarte au sucre', 29, 3),
 ("Sirop d'érable", 29, 2)]

Si un attribut sur lequel porte un critère de tri contient la valeur « **NULL** », les lignes correspondantes sont affichées en dernier. Oracle traite les valeurs « **NULL** » comme si elles étaient des valeurs infinies.

In [36]:
%sql \
SELECT NOM,PRENOM,SALAIRE,COMMISSION\
FROM EMPLOYES\
ORDER BY COMMISSION

 * oracle+cx_oracle://stag26:***@51.91.76.248:15440/coursdb
0 rows affected.

[('Petit', 'Michel', Decimal('6300'), Decimal('20')),
 ('Gregoire', 'Renée', Decimal('8000'), Decimal('30')),
 ('Michiels', 'François', Decimal('5500'), Decimal('40')),
 ('Dupouey', 'Pierre', Decimal('5500'), Decimal('40')),
 ('Jenny', 'Michel', Decimal('9800'), Decimal('150')),
 ('Arrambide', 'Jean Pierre', Decimal('5400'), Decimal('190')),
 ('Piroddi', 'Nathalie', Decimal('6700'), Decimal('190')),
 ('Mangeard', 'Jocelyne', Decimal('8200'), Decimal('190')),
 ('Dohr', 'Sylvie', Decimal('8200'), Decimal('200')),
 ('Lamarre', 'Eric', Decimal('7800'), Decimal('200')),
 ('Poidatz', 'Benoît', Decimal('6600'), Decimal('200')),
 ('Leverling', 'Janet', Decimal('7400'), Decimal('240')),
 ('Rivat', 'Jean-Louis', Decimal('5200'), Decimal('310')),
 ('Teixeira', 'Claudia', Decimal('6800'), Decimal('330')),
 ('Perny', 'Sylvie', Decimal('6500'), Decimal('340')),
 ('Blard', 'Jean-Benoît', Decimal('5900'), Decimal('340')),
 ('Suyama', 'Michael', Decimal('8400'), Decimal('400')),
 ('Capharsie', 'Gérard', Decimal('9400'), Decimal('410')),
 ('Duriez', 'Maurice', Decimal('9100'), Decimal('420')),
 ('Guillossou', 'Nadine', Decimal('5200'), Decimal('470')),
 ('Zonca', 'Virginie', Decimal('6700'), Decimal('470')),
 ('Dodsworth', 'Anne', Decimal('8800'), Decimal('490')),
 ('Delorgue', 'Jean', Decimal('5900'), Decimal('510')),
 ('Perret', 'Laurence', Decimal('9500'), Decimal('520')),
 ('Lefebvre', 'Michel', Decimal('9200'), Decimal('530')),
 ('Damas', 'Lydiane', Decimal('7700'), Decimal('530')),
 ('Cazade', 'Anne-Claire', Decimal('7200'), Decimal('550')),
 ('Canu', 'Christian', Decimal('5800'), Decimal('550')),
 ('Rollet', 'Philippe', Decimal('5000'), Decimal('570')),
 ('Cheutin', 'Corinne', Decimal('10000'), Decimal('570')),
 ('Idesheim', 'Annick', Decimal('7300'), Decimal('600')),
 ('Valot', 'Alain', Decimal('9200'), Decimal('680')),
 ('Bettan', 'Henri-Michel', Decimal('5500'), Decimal('690')),
 ('Bodard', 'René', Decimal('5500'), Decimal('720')),
 ('Cleret', 'Doris', Decimal('7900'), Decimal('720')),
 ('Viry', 'Yvan', Decimal('6700'), Decimal('740')),
 ('Aubert', 'Maria', Decimal('5100'), Decimal('750')),
 ('Bazart', 'Régis', Decimal('8900'), Decimal('760')),
 ('Coutou', 'Myriam', Decimal('6900'), Decimal('770')),
 ('Destenay', 'Agnès', Decimal('9900'), Decimal('790')),
 ('Nocella', 'Guy', Decimal('7600'), Decimal('910')),
 ('Cremel', 'Brigitte', Decimal('6900'), Decimal('910')),
 ('Di Clemente', 'Luc', Decimal('8400'), Decimal('920')),
 ('Peacock', 'Margaret', Decimal('6100'), Decimal('930')),
 ('Besse', 'José', Decimal('9900'), Decimal('940')),
 ('Berlioz', 'Jacques', Decimal('9400'), Decimal('980')),
 ('Griner', 'Florence', Decimal('8100'), Decimal('980')),
 ('Alvarez', 'Marcel', Decimal('7200'), Decimal('1010')),
 ('Jacquot', 'Philippe', Decimal('8900'), Decimal('1030')),
 ('King', 'Robert', Decimal('7200'), Decimal('1040')),
 ('Charles', 'Philippe', Decimal('6000'), Decimal('1080')),
 ('Silberreiss', 'Albert', Decimal('9200'), Decimal('1100')),
 ('Falatik', 'Bernard', Decimal('7600'), Decimal('1100')),
 ('Weiss', 'Sylvie', Decimal('6600'), Decimal('1110')),
 ('Montesinos', 'Aline', Decimal('8700'), Decimal('1130')),
 ('Malejac', 'Yannick', Decimal('8700'), Decimal('1130')),
 ('Mure', 'Guy', Decimal('8200'), Decimal('1140')),
 ('Jeandel', 'Véronique', Decimal('9200'), Decimal('1150')),
 ('Seigne', 'Marie-Pierre', Decimal('9600'), Decimal('1160')),
 ('Herve', 'Didier', Decimal('6700'), Decimal('1170')),
 ('Barre', 'Jean-Paul', Decimal('8800'), Decimal('1220')),
 ('Thimoleon', 'Georges', Decimal('8000'), Decimal('1270')),
 ('Marchand', 'Dominique', Decimal('6900'), Decimal('1280')),
 ('Maillard', 'Corinne', Decimal('6600'), Decimal('1300')),
 ('Thomas', 'Patricia', Decimal('7100'), Decimal('1310')),
 ('Steiner', 'Jean', Decimal('5400'), Decimal('1310')),
 ('Pagani', 'Hector', Decimal('6500'), Decimal('1330')),
 ('Lombard', 'Christiane', Decimal('6400'), Decimal('1350')),
 ('Clement', 'Valérie', Decimal('7200'), Decimal('1370')),
 ('Regner', 'Charles', Decimal('9300'), Decimal('1380')),
 ('Brunet', 'Jean-Luc', Decimal('6600'), Decimal('1400')),
 ('Messelier', 'Philippe', Decimal('9500'), Decimal('1470')),
 ('Gardeil', 'Henri', Decimal('7800'), Decimal('1520')),
 ('Chaussende', 'Maurice', Decimal('6600'), Decimal('1530')),
 ('Twardowski', 'Colette', Decimal('9400'), Decimal('1540')),
 ('Marielle', 'Michel', Decimal('7100'), Decimal('1550')),
 ('Maurousset', 'James', Decimal('8100'), Decimal('1560')),
 ('Espeche', 'Eric', Decimal('6500'), Decimal('1580')),
 ('Kremser', 'Arnaud', Decimal('6000'), Decimal('1610')),
 ('Hanriot', 'Catherine', Decimal('8300'), Decimal('1700')),
 ('Davolio', 'Nancy', Decimal('8200'), Decimal('1740')),
 ('Urbaniak', 'Isabelle', Decimal('7000'), Decimal('1760')),
 ('Kessler', 'Marc', Decimal('6800'), Decimal('1780')),
 ('Courty', 'Jean-Louis', Decimal('9900'), Decimal('1800')),
 ('Gerard', 'Sylvie', Decimal('8200'), Decimal('1800')),
 ('Pequignot', 'Guy', Decimal('6200'), Decimal('1820')),
 ('Aubry', 'Jean-Claude', Decimal('9500'), Decimal('1850')),
 ('Frederic', 'Jean Marie', Decimal('8100'), Decimal('1870')),
 ('Letertre', 'Sylvie', Decimal('5600'), Decimal('1890')),
 ('Tourtel', 'Nicole', Decimal('8100'), Decimal('1920')),
 ('Mennetrier', 'Alexandra', Decimal('8700'), Decimal('1970')),
 ('Burst', 'Jean-Yves', Decimal('7700'), Decimal('1980')),
 ('Ragon', 'André', Decimal('13000'), Decimal('5980')),
 ('Belin', 'Chantal', Decimal('10000'), Decimal('10640')),
 ('Leger', 'Pierre', Decimal('19000'), Decimal('11150')),
 ('Chambaud', 'Axelle', Decimal('12000'), Decimal('11600')),
 ('Buchanan', 'Steven', Decimal('13000'), Decimal('12940')),
 ('Splingart', 'Lydia', Decimal('16000'), Decimal('16480')),
 ('Guerdon', 'Béatrice', Decimal('1700'), None),
 ('Grangirard', 'Patricia', Decimal('1700'), None),
 ('Etienne', 'Brigitte', Decimal('2000'), None),
 ('Giroux', 'Jean-Claude', Decimal('150000'), None),
 ('Devie', 'Thérèse', Decimal('1540'), None),
 ('Callahan', 'Laura', Decimal('1200'), None),
 ('Lampis', 'Gabrielle', Decimal('1300'), None),
 ('Pouetre', 'Camille-Hélène', Decimal('2000'), None),
 ('Poupard', 'Claudette', Decimal('1800'), None),
 ('Brasseur', 'Hervé', Decimal('147000'), None),
 ('Fuller', 'Andrew', Decimal('96000'), None),
 ('Ziliox', 'Francoise', Decimal('1900'), None),
 ('Maurer', 'Véronique', Decimal('1400'), None)]

In [37]:
%sql \
SELECT NOM,PRENOM,SALAIRE,COMMISSION\
FROM EMPLOYES\
ORDER BY COMMISSION NULLS FIRST

 * oracle+cx_oracle://stag26:***@51.91.76.248:15440/coursdb
0 rows affected.

[('Ziliox', 'Francoise', Decimal('1900'), None),
 ('Guerdon', 'Béatrice', Decimal('1700'), None),
 ('Grangirard', 'Patricia', Decimal('1700'), None),
 ('Devie', 'Thérèse', Decimal('1540'), None),
 ('Maurer', 'Véronique', Decimal('1400'), None),
 ('Poupard', 'Claudette', Decimal('1800'), None),
 ('Fuller', 'Andrew', Decimal('96000'), None),
 ('Etienne', 'Brigitte', Decimal('2000'), None),
 ('Lampis', 'Gabrielle', Decimal('1300'), None),
 ('Callahan', 'Laura', Decimal('1200'), None),
 ('Brasseur', 'Hervé', Decimal('147000'), None),
 ('Pouetre', 'Camille-Hélène', Decimal('2000'), None),
 ('Giroux', 'Jean-Claude', Decimal('150000'), None),
 ('Petit', 'Michel', Decimal('6300'), Decimal('20')),
 ('Gregoire', 'Renée', Decimal('8000'), Decimal('30')),
 ('Michiels', 'François', Decimal('5500'), Decimal('40')),
 ('Dupouey', 'Pierre', Decimal('5500'), Decimal('40')),
 ('Jenny', 'Michel', Decimal('9800'), Decimal('150')),
 ('Arrambide', 'Jean Pierre', Decimal('5400'), Decimal('190')),
 ('Mangeard', 'Jocelyne', Decimal('8200'), Decimal('190')),
 ('Piroddi', 'Nathalie', Decimal('6700'), Decimal('190')),
 ('Lamarre', 'Eric', Decimal('7800'), Decimal('200')),
 ('Dohr', 'Sylvie', Decimal('8200'), Decimal('200')),
 ('Poidatz', 'Benoît', Decimal('6600'), Decimal('200')),
 ('Leverling', 'Janet', Decimal('7400'), Decimal('240')),
 ('Rivat', 'Jean-Louis', Decimal('5200'), Decimal('310')),
 ('Teixeira', 'Claudia', Decimal('6800'), Decimal('330')),
 ('Blard', 'Jean-Benoît', Decimal('5900'), Decimal('340')),
 ('Perny', 'Sylvie', Decimal('6500'), Decimal('340')),
 ('Suyama', 'Michael', Decimal('8400'), Decimal('400')),
 ('Capharsie', 'Gérard', Decimal('9400'), Decimal('410')),
 ('Duriez', 'Maurice', Decimal('9100'), Decimal('420')),
 ('Zonca', 'Virginie', Decimal('6700'), Decimal('470')),
 ('Guillossou', 'Nadine', Decimal('5200'), Decimal('470')),
 ('Dodsworth', 'Anne', Decimal('8800'), Decimal('490')),
 ('Delorgue', 'Jean', Decimal('5900'), Decimal('510')),
 ('Perret', 'Laurence', Decimal('9500'), Decimal('520')),
 ('Lefebvre', 'Michel', Decimal('9200'), Decimal('530')),
 ('Damas', 'Lydiane', Decimal('7700'), Decimal('530')),
 ('Cazade', 'Anne-Claire', Decimal('7200'), Decimal('550')),
 ('Canu', 'Christian', Decimal('5800'), Decimal('550')),
 ('Rollet', 'Philippe', Decimal('5000'), Decimal('570')),
 ('Cheutin', 'Corinne', Decimal('10000'), Decimal('570')),
 ('Idesheim', 'Annick', Decimal('7300'), Decimal('600')),
 ('Valot', 'Alain', Decimal('9200'), Decimal('680')),
 ('Bettan', 'Henri-Michel', Decimal('5500'), Decimal('690')),
 ('Cleret', 'Doris', Decimal('7900'), Decimal('720')),
 ('Bodard', 'René', Decimal('5500'), Decimal('720')),
 ('Viry', 'Yvan', Decimal('6700'), Decimal('740')),
 ('Aubert', 'Maria', Decimal('5100'), Decimal('750')),
 ('Bazart', 'Régis', Decimal('8900'), Decimal('760')),
 ('Coutou', 'Myriam', Decimal('6900'), Decimal('770')),
 ('Destenay', 'Agnès', Decimal('9900'), Decimal('790')),
 ('Nocella', 'Guy', Decimal('7600'), Decimal('910')),
 ('Cremel', 'Brigitte', Decimal('6900'), Decimal('910')),
 ('Di Clemente', 'Luc', Decimal('8400'), Decimal('920')),
 ('Peacock', 'Margaret', Decimal('6100'), Decimal('930')),
 ('Besse', 'José', Decimal('9900'), Decimal('940')),
 ('Berlioz', 'Jacques', Decimal('9400'), Decimal('980')),
 ('Griner', 'Florence', Decimal('8100'), Decimal('980')),
 ('Alvarez', 'Marcel', Decimal('7200'), Decimal('1010')),
 ('Jacquot', 'Philippe', Decimal('8900'), Decimal('1030')),
 ('King', 'Robert', Decimal('7200'), Decimal('1040')),
 ('Charles', 'Philippe', Decimal('6000'), Decimal('1080')),
 ('Silberreiss', 'Albert', Decimal('9200'), Decimal('1100')),
 ('Falatik', 'Bernard', Decimal('7600'), Decimal('1100')),
 ('Weiss', 'Sylvie', Decimal('6600'), Decimal('1110')),
 ('Montesinos', 'Aline', Decimal('8700'), Decimal('1130')),
 ('Malejac', 'Yannick', Decimal('8700'), Decimal('1130')),
 ('Mure', 'Guy', Decimal('8200'), Decimal('1140')),
 ('Jeandel', 'Véronique', Decimal('9200'), Decimal('1150')),
 ('Seigne', 'Marie-Pierre', Decimal('9600'), Decimal('1160')),
 ('Herve', 'Didier', Decimal('6700'), Decimal('1170')),
 ('Barre', 'Jean-Paul', Decimal('8800'), Decimal('1220')),
 ('Thimoleon', 'Georges', Decimal('8000'), Decimal('1270')),
 ('Marchand', 'Dominique', Decimal('6900'), Decimal('1280')),
 ('Maillard', 'Corinne', Decimal('6600'), Decimal('1300')),
 ('Thomas', 'Patricia', Decimal('7100'), Decimal('1310')),
 ('Steiner', 'Jean', Decimal('5400'), Decimal('1310')),
 ('Pagani', 'Hector', Decimal('6500'), Decimal('1330')),
 ('Lombard', 'Christiane', Decimal('6400'), Decimal('1350')),
 ('Clement', 'Valérie', Decimal('7200'), Decimal('1370')),
 ('Regner', 'Charles', Decimal('9300'), Decimal('1380')),
 ('Brunet', 'Jean-Luc', Decimal('6600'), Decimal('1400')),
 ('Messelier', 'Philippe', Decimal('9500'), Decimal('1470')),
 ('Gardeil', 'Henri', Decimal('7800'), Decimal('1520')),
 ('Chaussende', 'Maurice', Decimal('6600'), Decimal('1530')),
 ('Twardowski', 'Colette', Decimal('9400'), Decimal('1540')),
 ('Marielle', 'Michel', Decimal('7100'), Decimal('1550')),
 ('Maurousset', 'James', Decimal('8100'), Decimal('1560')),
 ('Espeche', 'Eric', Decimal('6500'), Decimal('1580')),
 ('Kremser', 'Arnaud', Decimal('6000'), Decimal('1610')),
 ('Hanriot', 'Catherine', Decimal('8300'), Decimal('1700')),
 ('Davolio', 'Nancy', Decimal('8200'), Decimal('1740')),
 ('Urbaniak', 'Isabelle', Decimal('7000'), Decimal('1760')),
 ('Kessler', 'Marc', Decimal('6800'), Decimal('1780')),
 ('Gerard', 'Sylvie', Decimal('8200'), Decimal('1800')),
 ('Courty', 'Jean-Louis', Decimal('9900'), Decimal('1800')),
 ('Pequignot', 'Guy', Decimal('6200'), Decimal('1820')),
 ('Aubry', 'Jean-Claude', Decimal('9500'), Decimal('1850')),
 ('Frederic', 'Jean Marie', Decimal('8100'), Decimal('1870')),
 ('Letertre', 'Sylvie', Decimal('5600'), Decimal('1890')),
 ('Tourtel', 'Nicole', Decimal('8100'), Decimal('1920')),
 ('Mennetrier', 'Alexandra', Decimal('8700'), Decimal('1970')),
 ('Burst', 'Jean-Yves', Decimal('7700'), Decimal('1980')),
 ('Ragon', 'André', Decimal('13000'), Decimal('5980')),
 ('Belin', 'Chantal', Decimal('10000'), Decimal('10640')),
 ('Leger', 'Pierre', Decimal('19000'), Decimal('11150')),
 ('Chambaud', 'Axelle', Decimal('12000'), Decimal('11600')),
 ('Buchanan', 'Steven', Decimal('13000'), Decimal('12940')),
 ('Splingart', 'Lydia', Decimal('16000'), Decimal('16480'))]

# La limitation d’enregistrements

In [38]:
%sql \
SELECT CODE_CATEGORIE,NOM_CATEGORIE \
FROM CATEGORIES  FETCH FIRST 3 ROWS ONLY

 * oracle+cx_oracle://stag26:***@51.91.76.248:15440/coursdb
0 rows affected.

[(1, 'Boissons'), (2, 'Condiments'), (3, 'Desserts')]

In [39]:
%sql \
SELECT CODE_CATEGORIE,NOM_CATEGORIE \
FROM CATEGORIES  OFFSET 5 ROWS FETCH NEXT 3 ROWS ONLY

 * oracle+cx_oracle://stag26:***@51.91.76.248:15440/coursdb
0 rows affected.

[(6, 'Viandes'), (7, 'Produits secs'), (8, 'Poissons et fruits de mer')]

In [40]:
%sql \
SELECT NOM_PRODUIT, UNITES_STOCK \
FROM PRODUITS \
ORDER BY UNITES_STOCK DESC NULLS LAST \
FETCH NEXT 5 ROWS ONLY

 * oracle+cx_oracle://stag26:***@51.91.76.248:15440/coursdb
0 rows affected.

[('Potato Chips', 200),
 ('Rhönbräu Klosterbier', 125),
 ('Green Tea', 125),
 ('Boston Crab Meat', 123),
 ("Grandma's Boysenberry Spread", 120)]

In [41]:
%sql \
SELECT NOM_PRODUIT, UNITES_STOCK \
FROM PRODUITS \
ORDER BY UNITES_STOCK DESC NULLS LAST \
FETCH NEXT 5 ROWS WITH TIES

 * oracle+cx_oracle://stag26:***@51.91.76.248:15440/coursdb
0 rows affected.

[('Potato Chips', 200),
 ('Rhönbräu Klosterbier', 125),
 ('Green Tea', 125),
 ('Boston Crab Meat', 123),
 ("Grandma's Boysenberry Spread", 120),
 ('Long Grain Rice - Gnocchi', 120),
 ('Crab Meat', 120)]

In [44]:
%sql \
SELECT NO_COMMANDE,REF_PRODUIT,QUANTITE,PRIX_UNITAIRE\
FROM DETAILS_COMMANDES FETCH NEXT 5 ROWS ONLY

 * oracle+cx_oracle://stag26:***@51.91.76.248:15440/coursdb
0 rows affected.

[(214994, 87, 34, Decimal('62.16')),
 (214994, 49, 89, Decimal('88.2')),
 (214994, 3, 53, Decimal('37.56')),
 (214994, 84, 104, Decimal('48.72')),
 (214994, 57, 125, Decimal('65.04'))]

# Atelier 2.1	Interrogation des données

## Projection
Écrivez les requêtes vous permettant d’afficher :
>> * Le nom, le prénom et la date de naissance de tous les employés de la société.<br>
>> * Le nom de la société, la ville et le pays de tous les fournisseurs.<br>
>> * La fonction de tous les employés.<br>
>> * Toutes les fonctions des employés de l’entreprise, chaque fonction doit être affichée une seule fois.<br>
>> * La liste des localités dans lesquelles la société a au moins un client.<br>

## Opérateurs
Créez les requêtes vous permettant d’afficher :
>> * Les produits commercialisés, la valeur du stock par produit et la valeur des produits commandés. Dans la table **PRODUITS**, vous trouvez les champs **UNITES_STOCK** et **UNITES_COMMANDEES** que vous multipliez par le **PRIX_UNITAIRE** pour retrouver les valeurs des deux stocks.<br>
>> * Le nom, le prénom, l’âge et l’ancienneté des employés, dans la société.<br>
>> * Le numéro de la commande, le temps écoulé entre la commande et la livraison de celle-ci ainsi que les frais de port.<br>

## Les ordres de tri
>> * Les employés par ordre alphabétique.<br>
>> * Les employés depuis le plus récemment embauché jusqu’au plus ancien.<br>
>> * Les fournisseurs dans l’ordre alphabétique de leur pays et ville de résidence.<br>
>> * Les employés par ordre alphabétique de leur fonction et du plus grand salaire au plus petit.<br>
>> * Les employés dans l’ordre de leur commission.<br>